import os
import sys

import psutil
from PySide2 import QtWidgets as QtW
from PySide2 import QtGui as QtG
from PySide2 import QtCore as QtC


MonospaceFont = QtG.QFont("Consolas")
MinimumWidth = QtW.QSizePolicy(QtW.QSizePolicy.Minimum, QtW.QSizePolicy.Preferred)
MinimumHeight = QtW.QSizePolicy(QtW.QSizePolicy.Preferred, QtW.QSizePolicy.Minimum)


class Widgets:
    pass


class MainWindow(QtW.QMainWindow):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setWindowTitle("Starbound Server Manager")
        self.setWindowIcon(QtG.QIcon(os.path.join("resources", "images", "ssm-logo.png")))
        self.setMinimumSize(800, 500)
        self.setFont(MonospaceFont)
        self.widgets = Widgets()

        # Menu and Status
        self.top_menu = self.menuBar()
        self.widgets.file_menu = self.top_menu.addMenu("&File")
        self.widgets.exit_action = self.widgets.file_menu.addAction("E&xit")
        self.widgets.exit_action.triggered.connect(self.__exit_action__)
        self.widgets.help_menu = self.top_menu.addMenu("&Help")
        self.widgets.about_action = self.widgets.help_menu.addAction("&About")
        self.widgets.about_action.triggered.connect(self.__about_action__)

        self.widgets.status = self.statusBar()

        # Main Layout
        self.widgets.central_widget = QtW.QWidget()
        self.widgets.layout = QtW.QVBoxLayout()
        self.widgets.central_widget.setLayout(self.widgets.layout)
        self.setCentralWidget(self.widgets.central_widget)
        self.widgets.tab_widget = QtW.QTabWidget()
        self.widgets.layout.addWidget(self.widgets.tab_widget)

        # General Tab
        self.widgets.general = Widgets()
        self.widgets.general.widget = QtW.QWidget()
        self.widgets.general.layout = QtW.QGridLayout()
        self.widgets.general.widget.setLayout(self.widgets.general.layout)
        self.widgets.tab_widget.addTab(self.widgets.general.widget, "General")

        self.widgets.general.player_label = QtW.QLabel("Players")
        self.widgets.general.layout.addWidget(self.widgets.general.player_label, 0, 0)
        self.widgets.general.log_label = QtW.QLabel("Server Log")
        self.widgets.general.layout.addWidget(self.widgets.general.log_label, 0, 1)

        self.widgets.general.player_list = QtW.QListWidget()
        self.widgets.general.player_list.setSizePolicy(MinimumWidth)
        self.widgets.general.player_list.addItem(QtW.QListWidgetItem(QtG.QIcon(os.path.join("resources", "images", "ssm-logo.png")), "Test Item"))
        self.widgets.general.layout.addWidget(self.widgets.general.player_list, 1, 0, 4, 1)

        self.widgets.general.log_list = QtW.QListWidget()
        self.widgets.general.log_list.setVerticalScrollBarPolicy(QtC.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.widgets.general.log_list.addItem("[01:09:35] Server stopped")
        self.widgets.general.layout.addWidget(self.widgets.general.log_list, 1, 1)

        self.widgets.general.command_layout = QtW.QHBoxLayout()
        self.widgets.general.layout.addLayout(self.widgets.general.command_layout, 2, 1)
        self.widgets.general.command_edit = QtW.QLineEdit()
        self.widgets.general.command_layout.addWidget(self.widgets.general.command_edit)
        self.widgets.general.command_send = QtW.QPushButton("Send")
        self.widgets.general.command_send.clicked.connect(self.__general_command_send_clicked__)
        self.widgets.general.command_layout.addWidget(self.widgets.general.command_send)

        self.widgets.general.chat_label = QtW.QLabel("Chat Log")
        self.widgets.general.layout.addWidget(self.widgets.general.chat_label, 3, 1)
        self.widgets.general.chat_list = QtW.QListWidget()
        self.widgets.general.chat_list.setVerticalScrollBarPolicy(QtC.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.widgets.general.layout.addWidget(self.widgets.general.chat_list, 4, 1)

        self.widgets.general.controls_group = QtW.QGroupBox("Server Controls")
        self.widgets.general.controls_group.setSizePolicy(MinimumWidth)
        self.widgets.general.layout.addWidget(self.widgets.general.controls_group, 5, 0)
        self.widgets.general.controls_layout = QtW.QVBoxLayout()
        self.widgets.general.controls_group.setLayout(self.widgets.general.controls_layout)
        self.widgets.general.controls_start = QtW.QPushButton("Start")
        self.widgets.general.controls_start.clicked.connect(self.__general_controls_start_clicked__)
        self.widgets.general.controls_layout.addWidget(self.widgets.general.controls_start)
        self.widgets.general.controls_restart = QtW.QPushButton("Restart")
        self.widgets.general.controls_start.clicked.connect(self.__general_controls_restart_clicked__)
        self.widgets.general.controls_layout.addWidget(self.widgets.general.controls_restart)
        self.widgets.general.controls_stop = QtW.QPushButton("Stop")
        self.widgets.general.controls_start.clicked.connect(self.__general_controls_stop_clicked__)
        self.widgets.general.controls_layout.addWidget(self.widgets.general.controls_stop)

        self.widgets.general.info_group = QtW.QGroupBox("Information")
        self.widgets.general.layout.addWidget(self.widgets.general.info_group, 5, 1)
        self.widgets.general.info_layout = QtW.QGridLayout()
        self.widgets.general.info_group.setLayout(self.widgets.general.info_layout)
        self.widgets.general.info_status_label = QtW.QLabel("Status:")
        self.widgets.general.info_layout.addWidget(self.widgets.general.info_status_label, 0, 0)
        self.widgets.general.info_status_data = QtW.QLabel("Offline")
        self.widgets.general.info_layout.addWidget(self.widgets.general.info_status_data, 0, 1, 1, 3)
        self.widgets.general.info_uptime_label = QtW.QLabel("Uptime:")
        self.widgets.general.info_layout.addWidget(self.widgets.general.info_uptime_label, 1, 0)
        self.widgets.general.info_uptime_data = QtW.QLabel("0d 0h 0m 0s")
        self.widgets.general.info_layout.addWidget(self.widgets.general.info_uptime_data, 1, 1, 1, 3)
        self.widgets.general.info_version_label = QtW.QLabel("Version:")
        self.widgets.general.info_layout.addWidget(self.widgets.general.info_version_label, 2, 0)
        self.widgets.general.info_version_data = QtW.QLabel("Unknown")
        self.widgets.general.info_layout.addWidget(self.widgets.general.info_version_data, 2, 1, 1, 3)
        self.widgets.general.info_ip_label = QtW.QLabel("IP:")
        self.widgets.general.info_layout.addWidget(self.widgets.general.info_ip_label, 3, 0)
        self.widgets.general.info_ip_data = QtW.QLabel("0.0.0.0")
        self.widgets.general.info_layout.addWidget(self.widgets.general.info_ip_data, 3, 1)
        self.widgets.general.info_port_label = QtW.QLabel("Port:")
        self.widgets.general.info_layout.addWidget(self.widgets.general.info_port_label, 3, 2)
        self.widgets.general.info_port_data = QtW.QLabel("21025")
        self.widgets.general.info_layout.addWidget(self.widgets.general.info_port_data, 3, 3)
        self.widgets.general.info_connected_label = QtW.QLabel("Players Connected:")
        self.widgets.general.info_layout.addWidget(self.widgets.general.info_connected_label, 0, 4)
        self.widgets.general.info_connected_data = QtW.QLabel("0")
        self.widgets.general.info_layout.addWidget(self.widgets.general.info_connected_data, 0, 5)
        self.widgets.general.info_planets_label = QtW.QLabel("Loaded Planets:")
        self.widgets.general.info_layout.addWidget(self.widgets.general.info_planets_label, 1, 4)
        self.widgets.general.info_planets_data = QtW.QLabel("0")
        self.widgets.general.info_layout.addWidget(self.widgets.general.info_planets_data, 1, 5)
        self.widgets.general.info_ships_label = QtW.QLabel("Loaded Ships:")
        self.widgets.general.info_layout.addWidget(self.widgets.general.info_ships_label, 2, 4)
        self.widgets.general.info_ships_data = QtW.QLabel("0")
        self.widgets.general.info_layout.addWidget(self.widgets.general.info_ships_data, 2, 5)
        self.widgets.general.info_layout.setColumnStretch(1, 1)
        self.widgets.general.info_layout.setColumnStretch(3, 1)
        self.widgets.general.info_layout.setColumnStretch(5, 1)

        # Players Tab
        self.widgets.players = Widgets()
        self.widgets.players.widget = QtW.QWidget()
        self.widgets.players.layout = QtW.QVBoxLayout()
        self.widgets.players.widget.setLayout(self.widgets.players.layout)
        self.widgets.tab_widget.addTab(self.widgets.players.widget, "Players")

        self.widgets.players.current_players_layout = QtW.QHBoxLayout()
        self.widgets.players.layout.addLayout(self.widgets.players.current_players_layout)
        self.widgets.players.current_players_label = QtW.QLabel("Current Connected Players:")
        self.widgets.players.current_players_label.setSizePolicy(QtW.QSizePolicy(QtW.QSizePolicy.Minimum, QtW.QSizePolicy.Preferred))
        self.widgets.players.current_players_layout.addWidget(self.widgets.players.current_players_label)
        self.widgets.players.current_players_data = QtW.QLabel("0")
        self.widgets.players.current_players_data.setSizePolicy(QtW.QSizePolicy(QtW.QSizePolicy.Expanding, QtW.QSizePolicy.Preferred))
        self.widgets.players.current_players_layout.addWidget(self.widgets.players.current_players_data)
        self.widgets.players.current_players_table = QtW.QTableWidget()
        self.widgets.players.current_players_table.setColumnCount(6)
        self.widgets.players.current_players_table.setHorizontalHeaderItem(0, QtW.QTableWidgetItem("ID"))
        self.widgets.players.current_players_table.horizontalHeader().setSectionResizeMode(0, QtW.QHeaderView.ResizeToContents)
        self.widgets.players.current_players_table.setHorizontalHeaderItem(1, QtW.QTableWidgetItem("Name"))
        self.widgets.players.current_players_table.horizontalHeader().setSectionResizeMode(1, QtW.QHeaderView.Stretch)
        self.widgets.players.current_players_table.setHorizontalHeaderItem(2, QtW.QTableWidgetItem("Account"))
        self.widgets.players.current_players_table.horizontalHeader().setSectionResizeMode(2, QtW.QHeaderView.Stretch)
        self.widgets.players.current_players_table.setHorizontalHeaderItem(3, QtW.QTableWidgetItem("UUID"))
        self.widgets.players.current_players_table.horizontalHeader().setSectionResizeMode(3, QtW.QHeaderView.Stretch)
        self.widgets.players.current_players_table.setHorizontalHeaderItem(4, QtW.QTableWidgetItem("IP"))
        self.widgets.players.current_players_table.horizontalHeader().setSectionResizeMode(4, QtW.QHeaderView.Stretch)
        self.widgets.players.current_players_table.setHorizontalHeaderItem(5, QtW.QTableWidgetItem("Connection Time"))
        self.widgets.players.current_players_table.horizontalHeader().setSectionResizeMode(5, QtW.QHeaderView.Stretch)
        self.widgets.players.layout.addWidget(self.widgets.players.current_players_table)

        self.widgets.players.recent_players_layout = QtW.QHBoxLayout()
        self.widgets.players.layout.addLayout(self.widgets.players.recent_players_layout)
        self.widgets.players.recent_players_label = QtW.QLabel("Recent Connected Players:")
        self.widgets.players.recent_players_label.setSizePolicy(QtW.QSizePolicy(QtW.QSizePolicy.Minimum, QtW.QSizePolicy.Preferred))
        self.widgets.players.recent_players_layout.addWidget(self.widgets.players.recent_players_label)
        self.widgets.players.recent_players_data = QtW.QLabel("0")
        self.widgets.players.recent_players_data.setSizePolicy(QtW.QSizePolicy(QtW.QSizePolicy.Expanding, QtW.QSizePolicy.Preferred))
        self.widgets.players.recent_players_layout.addWidget(self.widgets.players.recent_players_data)
        self.widgets.players.recent_players_table = QtW.QTableWidget()
        self.widgets.players.recent_players_table.setColumnCount(6)
        self.widgets.players.recent_players_table.setHorizontalHeaderItem(0, QtW.QTableWidgetItem("Name"))
        self.widgets.players.recent_players_table.horizontalHeader().setSectionResizeMode(0, QtW.QHeaderView.Stretch)
        self.widgets.players.recent_players_table.setHorizontalHeaderItem(1, QtW.QTableWidgetItem("Account"))
        self.widgets.players.recent_players_table.horizontalHeader().setSectionResizeMode(1, QtW.QHeaderView.Stretch)
        self.widgets.players.recent_players_table.setHorizontalHeaderItem(2, QtW.QTableWidgetItem("UUID"))
        self.widgets.players.recent_players_table.horizontalHeader().setSectionResizeMode(2, QtW.QHeaderView.Stretch)
        self.widgets.players.recent_players_table.setHorizontalHeaderItem(3, QtW.QTableWidgetItem("IP"))
        self.widgets.players.recent_players_table.horizontalHeader().setSectionResizeMode(3, QtW.QHeaderView.Stretch)
        self.widgets.players.recent_players_table.setHorizontalHeaderItem(4, QtW.QTableWidgetItem("Last Connection"))
        self.widgets.players.recent_players_table.horizontalHeader().setSectionResizeMode(4, QtW.QHeaderView.Stretch)
        self.widgets.players.recent_players_table.setHorizontalHeaderItem(5, QtW.QTableWidgetItem("Last Disconnect"))
        self.widgets.players.recent_players_table.horizontalHeader().setSectionResizeMode(5, QtW.QHeaderView.Stretch)
        self.widgets.players.layout.addWidget(self.widgets.players.recent_players_table)

        # Universe Tab
        self.widgets.universe = Widgets()
        self.widgets.universe.widget = QtW.QWidget()
        self.widgets.universe.layout = QtW.QVBoxLayout()
        self.widgets.universe.widget.setLayout(self.widgets.universe.layout)
        self.widgets.tab_widget.addTab(self.widgets.universe.widget, "Universe")

        self.widgets.universe.current_planets_layout = QtW.QHBoxLayout()
        self.widgets.universe.layout.addLayout(self.widgets.universe.current_planets_layout)
        self.widgets.universe.current_planets_label = QtW.QLabel("Current Loaded Planets:")
        self.widgets.universe.current_planets_label.setSizePolicy(QtW.QSizePolicy(QtW.QSizePolicy.Minimum, QtW.QSizePolicy.Preferred))
        self.widgets.universe.current_planets_layout.addWidget(self.widgets.universe.current_planets_label)
        self.widgets.universe.current_planets_data = QtW.QLabel("0")
        self.widgets.universe.current_planets_data.setSizePolicy(QtW.QSizePolicy(QtW.QSizePolicy.Expanding, QtW.QSizePolicy.Preferred))
        self.widgets.universe.current_planets_layout.addWidget(self.widgets.universe.current_planets_data)
        self.widgets.universe.current_planets_table = QtW.QTableWidget()
        self.widgets.universe.current_planets_table.setColumnCount(8)
        self.widgets.universe.current_planets_table.setHorizontalHeaderItem(0, QtW.QTableWidgetItem("Type"))
        self.widgets.universe.current_planets_table.horizontalHeader().setSectionResizeMode(0, QtW.QHeaderView.ResizeToContents)
        self.widgets.universe.current_planets_table.setHorizontalHeaderItem(1, QtW.QTableWidgetItem("X"))
        self.widgets.universe.current_planets_table.horizontalHeader().setSectionResizeMode(1, QtW.QHeaderView.Stretch)
        self.widgets.universe.current_planets_table.setHorizontalHeaderItem(2, QtW.QTableWidgetItem("Y"))
        self.widgets.universe.current_planets_table.horizontalHeader().setSectionResizeMode(2, QtW.QHeaderView.Stretch)
        self.widgets.universe.current_planets_table.setHorizontalHeaderItem(3, QtW.QTableWidgetItem("System"))
        self.widgets.universe.current_planets_table.horizontalHeader().setSectionResizeMode(3, QtW.QHeaderView.Stretch)
        self.widgets.universe.current_planets_table.setHorizontalHeaderItem(4, QtW.QTableWidgetItem("Orbital"))
        self.widgets.universe.current_planets_table.horizontalHeader().setSectionResizeMode(4, QtW.QHeaderView.ResizeToContents)
        self.widgets.universe.current_planets_table.setHorizontalHeaderItem(5, QtW.QTableWidgetItem("Letter"))
        self.widgets.universe.current_planets_table.horizontalHeader().setSectionResizeMode(5, QtW.QHeaderView.ResizeToContents)
        self.widgets.universe.current_planets_table.setHorizontalHeaderItem(6, QtW.QTableWidgetItem("Time Loaded"))
        self.widgets.universe.current_planets_table.horizontalHeader().setSectionResizeMode(6, QtW.QHeaderView.Stretch)
        self.widgets.universe.current_planets_table.setHorizontalHeaderItem(7, QtW.QTableWidgetItem("Nickname"))
        self.widgets.universe.current_planets_table.horizontalHeader().setSectionResizeMode(7, QtW.QHeaderView.Stretch)
        self.widgets.universe.layout.addWidget(self.widgets.universe.current_planets_table)

        self.widgets.universe.recent_planets_layout = QtW.QHBoxLayout()
        self.widgets.universe.layout.addLayout(self.widgets.universe.recent_planets_layout)
        self.widgets.universe.recent_planets_label = QtW.QLabel("Recent Loaded Planets:")
        self.widgets.universe.recent_planets_label.setSizePolicy(QtW.QSizePolicy(QtW.QSizePolicy.Minimum, QtW.QSizePolicy.Preferred))
        self.widgets.universe.recent_planets_layout.addWidget(self.widgets.universe.recent_planets_label)
        self.widgets.universe.recent_planets_data = QtW.QLabel("0")
        self.widgets.universe.recent_planets_data.setSizePolicy(QtW.QSizePolicy(QtW.QSizePolicy.Expanding, QtW.QSizePolicy.Preferred))
        self.widgets.universe.recent_planets_layout.addWidget(self.widgets.universe.recent_planets_data)
        self.widgets.universe.recent_planets_table = QtW.QTableWidget()
        self.widgets.universe.recent_planets_table.setColumnCount(8)
        self.widgets.universe.recent_planets_table.setHorizontalHeaderItem(0, QtW.QTableWidgetItem("Type"))
        self.widgets.universe.recent_planets_table.horizontalHeader().setSectionResizeMode(0, QtW.QHeaderView.ResizeToContents)
        self.widgets.universe.recent_planets_table.setHorizontalHeaderItem(1, QtW.QTableWidgetItem("X"))
        self.widgets.universe.recent_planets_table.horizontalHeader().setSectionResizeMode(1, QtW.QHeaderView.Stretch)
        self.widgets.universe.recent_planets_table.setHorizontalHeaderItem(2, QtW.QTableWidgetItem("Y"))
        self.widgets.universe.recent_planets_table.horizontalHeader().setSectionResizeMode(2, QtW.QHeaderView.Stretch)
        self.widgets.universe.recent_planets_table.setHorizontalHeaderItem(3, QtW.QTableWidgetItem("System"))
        self.widgets.universe.recent_planets_table.horizontalHeader().setSectionResizeMode(3, QtW.QHeaderView.Stretch)
        self.widgets.universe.recent_planets_table.setHorizontalHeaderItem(4, QtW.QTableWidgetItem("Orbital"))
        self.widgets.universe.recent_planets_table.horizontalHeader().setSectionResizeMode(4, QtW.QHeaderView.ResizeToContents)
        self.widgets.universe.recent_planets_table.setHorizontalHeaderItem(5, QtW.QTableWidgetItem("Letter"))
        self.widgets.universe.recent_planets_table.horizontalHeader().setSectionResizeMode(5, QtW.QHeaderView.ResizeToContents)
        self.widgets.universe.recent_planets_table.setHorizontalHeaderItem(6, QtW.QTableWidgetItem("Time Loaded"))
        self.widgets.universe.recent_planets_table.horizontalHeader().setSectionResizeMode(6, QtW.QHeaderView.Stretch)
        self.widgets.universe.recent_planets_table.setHorizontalHeaderItem(7, QtW.QTableWidgetItem("Nickname"))
        self.widgets.universe.recent_planets_table.horizontalHeader().setSectionResizeMode(7, QtW.QHeaderView.Stretch)
        self.widgets.universe.layout.addWidget(self.widgets.universe.recent_planets_table)

        # Ships Tab
        self.widgets.ships = Widgets()
        self.widgets.ships.widget = QtW.QWidget()
        self.widgets.ships.layout = QtW.QVBoxLayout()
        self.widgets.ships.widget.setLayout(self.widgets.ships.layout)
        self.widgets.tab_widget.addTab(self.widgets.ships.widget, "Ships")

        self.widgets.ships.current_ships_layout = QtW.QHBoxLayout()
        self.widgets.ships.layout.addLayout(self.widgets.ships.current_ships_layout)
        self.widgets.ships.current_ships_label = QtW.QLabel("Current Ships:")
        self.widgets.ships.current_ships_label.setSizePolicy(QtW.QSizePolicy(QtW.QSizePolicy.Minimum, QtW.QSizePolicy.Preferred))
        self.widgets.ships.current_ships_layout.addWidget(self.widgets.ships.current_ships_label)
        self.widgets.ships.current_ships_data = QtW.QLabel("0")
        self.widgets.ships.current_ships_data.setSizePolicy(QtW.QSizePolicy(QtW.QSizePolicy.Expanding, QtW.QSizePolicy.Preferred))
        self.widgets.ships.current_ships_layout.addWidget(self.widgets.ships.current_ships_data)
        self.widgets.ships.current_ships_table = QtW.QTableWidget()
        self.widgets.ships.current_ships_table.setColumnCount(7)
        self.widgets.ships.current_ships_table.setHorizontalHeaderItem(0, QtW.QTableWidgetItem("Player"))
        self.widgets.ships.current_ships_table.horizontalHeader().setSectionResizeMode(0, QtW.QHeaderView.Stretch)
        self.widgets.ships.current_ships_table.setHorizontalHeaderItem(1, QtW.QTableWidgetItem("X"))
        self.widgets.ships.current_ships_table.horizontalHeader().setSectionResizeMode(1, QtW.QHeaderView.Stretch)
        self.widgets.ships.current_ships_table.setHorizontalHeaderItem(2, QtW.QTableWidgetItem("Y"))
        self.widgets.ships.current_ships_table.horizontalHeader().setSectionResizeMode(2, QtW.QHeaderView.Stretch)
        self.widgets.ships.current_ships_table.setHorizontalHeaderItem(3, QtW.QTableWidgetItem("System"))
        self.widgets.ships.current_ships_table.horizontalHeader().setSectionResizeMode(3, QtW.QHeaderView.Stretch)
        self.widgets.ships.current_ships_table.setHorizontalHeaderItem(4, QtW.QTableWidgetItem("Orbital"))
        self.widgets.ships.current_ships_table.horizontalHeader().setSectionResizeMode(4, QtW.QHeaderView.Stretch)
        self.widgets.ships.current_ships_table.setHorizontalHeaderItem(5, QtW.QTableWidgetItem("Letter"))
        self.widgets.ships.current_ships_table.horizontalHeader().setSectionResizeMode(5, QtW.QHeaderView.Stretch)
        self.widgets.ships.current_ships_table.setHorizontalHeaderItem(6, QtW.QTableWidgetItem("Time Loaded"))
        self.widgets.ships.current_ships_table.horizontalHeader().setSectionResizeMode(6, QtW.QHeaderView.Stretch)
        self.widgets.ships.layout.addWidget(self.widgets.ships.current_ships_table)

        self.widgets.ships.recent_ships_layout = QtW.QHBoxLayout()
        self.widgets.ships.layout.addLayout(self.widgets.ships.recent_ships_layout)
        self.widgets.ships.recent_ships_label = QtW.QLabel("Recent Ships:")
        self.widgets.ships.recent_ships_label.setSizePolicy(QtW.QSizePolicy(QtW.QSizePolicy.Minimum, QtW.QSizePolicy.Preferred))
        self.widgets.ships.recent_ships_layout.addWidget(self.widgets.ships.recent_ships_label)
        self.widgets.ships.recent_ships_data = QtW.QLabel("0")
        self.widgets.ships.recent_ships_data.setSizePolicy(QtW.QSizePolicy(QtW.QSizePolicy.Expanding, QtW.QSizePolicy.Preferred))
        self.widgets.ships.recent_ships_layout.addWidget(self.widgets.ships.recent_ships_data)
        self.widgets.ships.recent_ships_table = QtW.QTableWidget()
        self.widgets.ships.recent_ships_table.setColumnCount(8)
        self.widgets.ships.recent_ships_table.setHorizontalHeaderItem(0, QtW.QTableWidgetItem("Player"))
        self.widgets.ships.recent_ships_table.horizontalHeader().setSectionResizeMode(0, QtW.QHeaderView.Stretch)
        self.widgets.ships.recent_ships_table.setHorizontalHeaderItem(1, QtW.QTableWidgetItem("X"))
        self.widgets.ships.recent_ships_table.horizontalHeader().setSectionResizeMode(1, QtW.QHeaderView.Stretch)
        self.widgets.ships.recent_ships_table.setHorizontalHeaderItem(2, QtW.QTableWidgetItem("Y"))
        self.widgets.ships.recent_ships_table.horizontalHeader().setSectionResizeMode(2, QtW.QHeaderView.Stretch)
        self.widgets.ships.recent_ships_table.setHorizontalHeaderItem(3, QtW.QTableWidgetItem("System"))
        self.widgets.ships.recent_ships_table.horizontalHeader().setSectionResizeMode(3, QtW.QHeaderView.Stretch)
        self.widgets.ships.recent_ships_table.setHorizontalHeaderItem(4, QtW.QTableWidgetItem("Orbital"))
        self.widgets.ships.recent_ships_table.horizontalHeader().setSectionResizeMode(4, QtW.QHeaderView.Stretch)
        self.widgets.ships.recent_ships_table.setHorizontalHeaderItem(5, QtW.QTableWidgetItem("Letter"))
        self.widgets.ships.recent_ships_table.horizontalHeader().setSectionResizeMode(5, QtW.QHeaderView.Stretch)
        self.widgets.ships.recent_ships_table.setHorizontalHeaderItem(6, QtW.QTableWidgetItem("Time Loaded"))
        self.widgets.ships.recent_ships_table.horizontalHeader().setSectionResizeMode(6, QtW.QHeaderView.Stretch)
        self.widgets.ships.recent_ships_table.setHorizontalHeaderItem(7, QtW.QTableWidgetItem("Time Unloaded"))
        self.widgets.ships.recent_ships_table.horizontalHeader().setSectionResizeMode(7, QtW.QHeaderView.Stretch)
        self.widgets.ships.layout.addWidget(self.widgets.ships.recent_ships_table)

        # Player Tracking
        self.widgets.tracking = Widgets()
        self.widgets.tracking.widget = QtW.QWidget()
        self.widgets.tracking.layout = QtW.QVBoxLayout()
        self.widgets.tracking.widget.setLayout(self.widgets.tracking.layout)
        self.widgets.tab_widget.addTab(self.widgets.tracking.widget, "Tracking")

        self.widgets.tracking.player_tracking_label = QtW.QLabel("Tracking")

        # Events Log
        self.widgets.events = Widgets()
        self.widgets.events.widget = QtW.QWidget()
        self.widgets.events.layout = QtW.QVBoxLayout()
        self.widgets.events.widget.setLayout(self.widgets.events.layout)
        self.widgets.tab_widget.addTab(self.widgets.events.widget, "Events")

        # Statistics
        self.widgets.stats = Widgets()
        self.widgets.stats.widget = QtW.QWidget()
        self.widgets.stats.layout = QtW.QGridLayout()
        self.widgets.stats.widget.setLayout(self.widgets.stats.layout)
        self.widgets.tab_widget.addTab(self.widgets.stats.widget, "Statistics")

        self.widgets.stats.current_stats_group = QtW.QGroupBox("Currently:")
        self.widgets.stats.layout.addWidget(self.widgets.stats.current_stats_group, 0, 0)
        self.widgets.stats.current_stats_layout = QtW.QGridLayout()
        self.widgets.stats.current_stats_layout.setColumnStretch(1, 1)
        self.widgets.stats.current_stats_group.setLayout(self.widgets.stats.current_stats_layout)
        self.widgets.stats.current_stats_players_label = QtW.QLabel("Players:")
        self.widgets.stats.current_stats_layout.addWidget(self.widgets.stats.current_stats_players_label, 0, 0)
        self.widgets.stats.current_stats_players_data = QtW.QLabel("0")
        self.widgets.stats.current_stats_players_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.current_stats_layout.addWidget(self.widgets.stats.current_stats_players_data, 0, 1)
        self.widgets.stats.current_stats_planets_label = QtW.QLabel("Planets:")
        self.widgets.stats.current_stats_layout.addWidget(self.widgets.stats.current_stats_planets_label, 1, 0)
        self.widgets.stats.current_stats_planets_data = QtW.QLabel("0")
        self.widgets.stats.current_stats_planets_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.current_stats_layout.addWidget(self.widgets.stats.current_stats_planets_data, 1, 1)
        self.widgets.stats.current_stats_ships_label = QtW.QLabel("Ships:")
        self.widgets.stats.current_stats_layout.addWidget(self.widgets.stats.current_stats_ships_label, 2, 0)
        self.widgets.stats.current_stats_ships_data = QtW.QLabel("0")
        self.widgets.stats.current_stats_ships_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.current_stats_layout.addWidget(self.widgets.stats.current_stats_ships_data, 2, 1)
        self.widgets.stats.current_stats_layout.setRowStretch(3, 1)

        self.widgets.stats.current_session_group = QtW.QGroupBox("Current Session:")
        self.widgets.stats.layout.addWidget(self.widgets.stats.current_session_group, 0, 1)
        self.widgets.stats.current_session_layout = QtW.QGridLayout()
        self.widgets.stats.current_session_layout.setColumnStretch(1, 1)
        self.widgets.stats.current_session_group.setLayout(self.widgets.stats.current_session_layout)
        self.widgets.stats.current_session_players_login_label = QtW.QLabel("Players Login:")
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_players_login_label, 0, 0)
        self.widgets.stats.current_session_players_login_data = QtW.QLabel("0")
        self.widgets.stats.current_session_players_login_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_players_login_data, 0, 1)
        self.widgets.stats.current_session_players_logout_label = QtW.QLabel("Players Logout:")
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_players_logout_label, 1, 0)
        self.widgets.stats.current_session_players_logout_data = QtW.QLabel("0")
        self.widgets.stats.current_session_players_logout_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_players_logout_data, 1, 1)
        self.widgets.stats.current_session_layout.addWidget(QtW.QLabel(), 2, 0)
        self.widgets.stats.current_session_planet_loaded_label = QtW.QLabel("Planets Loaded:")
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_planet_loaded_label, 3, 0)
        self.widgets.stats.current_session_planet_loaded_data = QtW.QLabel("0")
        self.widgets.stats.current_session_planet_loaded_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_planet_loaded_data, 3, 1)
        self.widgets.stats.current_session_planet_unloaded_label = QtW.QLabel("Planets Unloaded:")
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_planet_unloaded_label, 4, 0)
        self.widgets.stats.current_session_planet_unloaded_data = QtW.QLabel("0")
        self.widgets.stats.current_session_planet_unloaded_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_planet_unloaded_data, 4, 1)
        self.widgets.stats.current_session_layout.addWidget(QtW.QLabel(), 5, 0)
        self.widgets.stats.current_session_ships_loaded_label = QtW.QLabel("Ships Loaded:")
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_ships_loaded_label, 6, 0)
        self.widgets.stats.current_session_ships_loaded_data = QtW.QLabel("0")
        self.widgets.stats.current_session_ships_loaded_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_ships_loaded_data, 6, 1)
        self.widgets.stats.current_session_ships_unloaded_label = QtW.QLabel("Ships Unloaded:")
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_ships_unloaded_label, 7, 0)
        self.widgets.stats.current_session_ships_unloaded_data = QtW.QLabel("0")
        self.widgets.stats.current_session_ships_unloaded_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_ships_unloaded_data, 7, 1)
        self.widgets.stats.current_session_layout.addWidget(QtW.QLabel(), 8, 0)
        self.widgets.stats.current_session_players_warped_label = QtW.QLabel("Players Warped:")
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_players_warped_label, 9, 0)
        self.widgets.stats.current_session_players_warped_data = QtW.QLabel("0")
        self.widgets.stats.current_session_players_warped_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_players_warped_data, 9, 1)
        self.widgets.stats.current_session_ships_travel_label = QtW.QLabel("Ships Traveled:")
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_ships_travel_label, 10, 0)
        self.widgets.stats.current_session_ships_travel_data = QtW.QLabel("0")
        self.widgets.stats.current_session_ships_travel_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_ships_travel_data, 10, 1)
        self.widgets.stats.current_session_layout.addWidget(QtW.QLabel(), 11, 0)
        self.widgets.stats.current_session_server_events_label = QtW.QLabel("Server Events:")
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_server_events_label, 12, 0)
        self.widgets.stats.current_session_server_events_data = QtW.QLabel("0")
        self.widgets.stats.current_session_server_events_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_server_events_data, 12, 1)
        self.widgets.stats.current_session_events_label = QtW.QLabel("Events:")
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_events_label, 13, 0)
        self.widgets.stats.current_session_events_data = QtW.QLabel("0")
        self.widgets.stats.current_session_events_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_events_data, 13, 1)
        self.widgets.stats.current_session_layout.addWidget(QtW.QLabel(), 14, 0)
        self.widgets.stats.current_session_chat_entries_label = QtW.QLabel("Chat Entries:")
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_chat_entries_label, 15, 0)
        self.widgets.stats.current_session_chat_entries_data = QtW.QLabel("0")
        self.widgets.stats.current_session_chat_entries_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_chat_entries_data, 15, 1)
        self.widgets.stats.current_session_layout.addWidget(QtW.QLabel(), 16, 0)
        self.widgets.stats.current_session_up_time_label = QtW.QLabel("Up Time:")
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_up_time_label, 17, 0)
        self.widgets.stats.current_session_up_time_data = QtW.QLabel("0d 0h 0m 0s")
        self.widgets.stats.current_session_up_time_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.current_session_layout.addWidget(self.widgets.stats.current_session_up_time_data, 17, 1)
        self.widgets.stats.current_session_layout.setRowStretch(18, 1)

        self.widgets.stats.past_session_group = QtW.QGroupBox("Past Session:")
        self.widgets.stats.layout.addWidget(self.widgets.stats.past_session_group, 0, 2)
        self.widgets.stats.past_session_layout = QtW.QGridLayout()
        self.widgets.stats.past_session_layout.setColumnStretch(1, 1)
        self.widgets.stats.past_session_group.setLayout(self.widgets.stats.past_session_layout)
        self.widgets.stats.past_session_players_login_label = QtW.QLabel("Players Login:")
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_players_login_label, 0, 0)
        self.widgets.stats.past_session_players_login_data = QtW.QLabel("0")
        self.widgets.stats.past_session_players_login_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_players_login_data, 0, 1)
        self.widgets.stats.past_session_players_logout_label = QtW.QLabel("Players Logout:")
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_players_logout_label, 1, 0)
        self.widgets.stats.past_session_players_logout_data = QtW.QLabel("0")
        self.widgets.stats.past_session_players_logout_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_players_logout_data, 1, 1)
        self.widgets.stats.past_session_layout.addWidget(QtW.QLabel(), 2, 0)
        self.widgets.stats.past_session_planet_loaded_label = QtW.QLabel("Planets Loaded:")
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_planet_loaded_label, 3, 0)
        self.widgets.stats.past_session_planet_loaded_data = QtW.QLabel("0")
        self.widgets.stats.past_session_planet_loaded_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_planet_loaded_data, 3, 1)
        self.widgets.stats.past_session_planet_unloaded_label = QtW.QLabel("Planets Unloaded:")
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_planet_unloaded_label, 4, 0)
        self.widgets.stats.past_session_planet_unloaded_data = QtW.QLabel("0")
        self.widgets.stats.past_session_planet_unloaded_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_planet_unloaded_data, 4, 1)
        self.widgets.stats.past_session_layout.addWidget(QtW.QLabel(), 5, 0)
        self.widgets.stats.past_session_ships_loaded_label = QtW.QLabel("Ships Loaded:")
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_ships_loaded_label, 6, 0)
        self.widgets.stats.past_session_ships_loaded_data = QtW.QLabel("0")
        self.widgets.stats.past_session_ships_loaded_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_ships_loaded_data, 6, 1)
        self.widgets.stats.past_session_ships_unloaded_label = QtW.QLabel("Ships Unloaded:")
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_ships_unloaded_label, 7, 0)
        self.widgets.stats.past_session_ships_unloaded_data = QtW.QLabel("0")
        self.widgets.stats.past_session_ships_unloaded_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_ships_unloaded_data, 7, 1)
        self.widgets.stats.past_session_layout.addWidget(QtW.QLabel(), 8, 0)
        self.widgets.stats.past_session_players_warped_label = QtW.QLabel("Players Warped:")
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_players_warped_label, 9, 0)
        self.widgets.stats.past_session_players_warped_data = QtW.QLabel("0")
        self.widgets.stats.past_session_players_warped_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_players_warped_data, 9, 1)
        self.widgets.stats.past_session_ships_travel_label = QtW.QLabel("Ships Traveled:")
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_ships_travel_label, 10, 0)
        self.widgets.stats.past_session_ships_travel_data = QtW.QLabel("0")
        self.widgets.stats.past_session_ships_travel_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_ships_travel_data, 10, 1)
        self.widgets.stats.past_session_layout.addWidget(QtW.QLabel(), 11, 0)
        self.widgets.stats.past_session_server_events_label = QtW.QLabel("Server Events:")
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_server_events_label, 12, 0)
        self.widgets.stats.past_session_server_events_data = QtW.QLabel("0")
        self.widgets.stats.past_session_server_events_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_server_events_data, 12, 1)
        self.widgets.stats.past_session_events_label = QtW.QLabel("Events:")
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_events_label, 13, 0)
        self.widgets.stats.past_session_events_data = QtW.QLabel("0")
        self.widgets.stats.past_session_events_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_events_data, 13, 1)
        self.widgets.stats.past_session_layout.addWidget(QtW.QLabel(), 14, 0)
        self.widgets.stats.past_session_chat_entries_label = QtW.QLabel("Chat Entries:")
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_chat_entries_label, 15, 0)
        self.widgets.stats.past_session_chat_entries_data = QtW.QLabel("0")
        self.widgets.stats.past_session_chat_entries_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_chat_entries_data, 15, 1)
        self.widgets.stats.past_session_layout.addWidget(QtW.QLabel(), 16, 0)
        self.widgets.stats.past_session_up_time_label = QtW.QLabel("Up Time:")
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_up_time_label, 17, 0)
        self.widgets.stats.past_session_up_time_data = QtW.QLabel("0d 0h 0m 0s")
        self.widgets.stats.past_session_up_time_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.past_session_layout.addWidget(self.widgets.stats.past_session_up_time_data, 17, 1)
        self.widgets.stats.past_session_layout.setRowStretch(18, 1)

        self.widgets.stats.overall_group = QtW.QGroupBox("Overall:")
        self.widgets.stats.layout.addWidget(self.widgets.stats.overall_group, 0, 3)
        self.widgets.stats.overall_layout = QtW.QGridLayout()
        self.widgets.stats.overall_layout.setColumnStretch(1, 1)
        self.widgets.stats.overall_group.setLayout(self.widgets.stats.overall_layout)
        self.widgets.stats.overall_players_login_label = QtW.QLabel("Players Login:")
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_players_login_label, 0, 0)
        self.widgets.stats.overall_players_login_data = QtW.QLabel("0")
        self.widgets.stats.overall_players_login_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_players_login_data, 0, 1)
        self.widgets.stats.overall_players_logout_label = QtW.QLabel("Players Logout:")
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_players_logout_label, 1, 0)
        self.widgets.stats.overall_players_logout_data = QtW.QLabel("0")
        self.widgets.stats.overall_players_logout_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_players_logout_data, 1, 1)
        self.widgets.stats.overall_layout.addWidget(QtW.QLabel(), 2, 0)
        self.widgets.stats.overall_planet_loaded_label = QtW.QLabel("Planets Loaded:")
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_planet_loaded_label, 3, 0)
        self.widgets.stats.overall_planet_loaded_data = QtW.QLabel("0")
        self.widgets.stats.overall_planet_loaded_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_planet_loaded_data, 3, 1)
        self.widgets.stats.overall_planet_unloaded_label = QtW.QLabel("Planets Unloaded:")
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_planet_unloaded_label, 4, 0)
        self.widgets.stats.overall_planet_unloaded_data = QtW.QLabel("0")
        self.widgets.stats.overall_planet_unloaded_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_planet_unloaded_data, 4, 1)
        self.widgets.stats.overall_layout.addWidget(QtW.QLabel(), 5, 0)
        self.widgets.stats.overall_ships_loaded_label = QtW.QLabel("Ships Loaded:")
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_ships_loaded_label, 6, 0)
        self.widgets.stats.overall_ships_loaded_data = QtW.QLabel("0")
        self.widgets.stats.overall_ships_loaded_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_ships_loaded_data, 6, 1)
        self.widgets.stats.overall_ships_unloaded_label = QtW.QLabel("Ships Unloaded:")
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_ships_unloaded_label, 7, 0)
        self.widgets.stats.overall_ships_unloaded_data = QtW.QLabel("0")
        self.widgets.stats.overall_ships_unloaded_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_ships_unloaded_data, 7, 1)
        self.widgets.stats.overall_layout.addWidget(QtW.QLabel(), 8, 0)
        self.widgets.stats.overall_players_warped_label = QtW.QLabel("Players Warped:")
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_players_warped_label, 9, 0)
        self.widgets.stats.overall_players_warped_data = QtW.QLabel("0")
        self.widgets.stats.overall_players_warped_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_players_warped_data, 9, 1)
        self.widgets.stats.overall_ships_travel_label = QtW.QLabel("Ships Traveled:")
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_ships_travel_label, 10, 0)
        self.widgets.stats.overall_ships_travel_data = QtW.QLabel("0")
        self.widgets.stats.overall_ships_travel_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_ships_travel_data, 10, 1)
        self.widgets.stats.overall_layout.addWidget(QtW.QLabel(), 11, 0)
        self.widgets.stats.overall_server_events_label = QtW.QLabel("Server Events:")
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_server_events_label, 12, 0)
        self.widgets.stats.overall_server_events_data = QtW.QLabel("0")
        self.widgets.stats.overall_server_events_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_server_events_data, 12, 1)
        self.widgets.stats.overall_events_label = QtW.QLabel("Events:")
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_events_label, 13, 0)
        self.widgets.stats.overall_events_data = QtW.QLabel("0")
        self.widgets.stats.overall_events_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_events_data, 13, 1)
        self.widgets.stats.overall_layout.addWidget(QtW.QLabel(), 14, 0)
        self.widgets.stats.overall_chat_entries_label = QtW.QLabel("Chat Entries:")
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_chat_entries_label, 15, 0)
        self.widgets.stats.overall_chat_entries_data = QtW.QLabel("0")
        self.widgets.stats.overall_chat_entries_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_chat_entries_data, 15, 1)
        self.widgets.stats.overall_layout.addWidget(QtW.QLabel(), 16, 0)
        self.widgets.stats.overall_up_time_label = QtW.QLabel("Up Time:")
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_up_time_label, 17, 0)
        self.widgets.stats.overall_up_time_data = QtW.QLabel("0d 0h 0m 0s")
        self.widgets.stats.overall_up_time_data.setAlignment(QtC.Qt.AlignRight)
        self.widgets.stats.overall_layout.addWidget(self.widgets.stats.overall_up_time_data, 17, 1)
        self.widgets.stats.overall_layout.setRowStretch(18, 1)

        self.widgets.stats.resource_group = QtW.QGroupBox("Resource Usage:")
        self.widgets.stats.layout.addWidget(self.widgets.stats.resource_group, 1, 0, 1, 2)
        self.widgets.stats.resource_layout = QtW.QGridLayout()
        self.widgets.stats.resource_layout.setColumnStretch(1, 1)
        self.widgets.stats.resource_layout.setColumnStretch(3, 1)
        self.widgets.stats.resource_group.setLayout(self.widgets.stats.resource_layout)
        self.widgets.stats.resource_cpu_label = QtW.QLabel("CPU Usage:")
        self.widgets.stats.resource_layout.addWidget(self.widgets.stats.resource_cpu_label, 0, 0, 1, 2)
        self.widgets.stats.resource_cpu_gui_label = QtW.QLabel("SSM:")
        self.widgets.stats.resource_layout.addWidget(self.widgets.stats.resource_cpu_gui_label, 1, 0)
        self.widgets.stats.resource_cpu_gui_data = QtW.QLabel("0%")
        self.widgets.stats.resource_layout.addWidget(self.widgets.stats.resource_cpu_gui_data, 1, 1)
        self.widgets.stats.resource_cpu_server_label = QtW.QLabel("Server:")
        self.widgets.stats.resource_layout.addWidget(self.widgets.stats.resource_cpu_server_label, 2, 0)
        self.widgets.stats.resource_cpu_server_data = QtW.QLabel("0%")
        self.widgets.stats.resource_layout.addWidget(self.widgets.stats.resource_cpu_server_data, 2, 1)
        self.widgets.stats.resource_cpu_total_label = QtW.QLabel("Total:")
        self.widgets.stats.resource_layout.addWidget(self.widgets.stats.resource_cpu_total_label, 3, 0)
        self.widgets.stats.resource_cpu_total_data = QtW.QLabel("0%")
        self.widgets.stats.resource_layout.addWidget(self.widgets.stats.resource_cpu_total_data, 3, 1)
        self.widgets.stats.resource_ram_label = QtW.QLabel("RAM Usage:")
        self.widgets.stats.resource_layout.addWidget(self.widgets.stats.resource_ram_label, 0, 2, 1, 2)
        self.widgets.stats.resource_ram_gui_label = QtW.QLabel("SSM:")
        self.widgets.stats.resource_layout.addWidget(self.widgets.stats.resource_ram_gui_label, 1, 2)
        self.widgets.stats.resource_ram_gui_data = QtW.QLabel("0%")
        self.widgets.stats.resource_layout.addWidget(self.widgets.stats.resource_ram_gui_data, 1, 3)
        self.widgets.stats.resource_ram_server_label = QtW.QLabel("Server:")
        self.widgets.stats.resource_layout.addWidget(self.widgets.stats.resource_ram_server_label, 2, 2)
        self.widgets.stats.resource_ram_server_data = QtW.QLabel("0%")
        self.widgets.stats.resource_layout.addWidget(self.widgets.stats.resource_ram_server_data, 2, 3)
        self.widgets.stats.resource_ram_total_label = QtW.QLabel("Total:")
        self.widgets.stats.resource_layout.addWidget(self.widgets.stats.resource_ram_total_label, 3, 2)
        self.widgets.stats.resource_ram_total_data = QtW.QLabel("0%")
        self.widgets.stats.resource_layout.addWidget(self.widgets.stats.resource_ram_total_data, 3, 3)

        self.widgets.stats.layout.setRowStretch(2, 1)

        # Server Config Tab

        # Timers
        self.resource_timer = QtC.QTimer()
        self.resource_timer.setInterval(2000)
        self.resource_timer.timeout.connect(self.__update_resource_usage__)
        self.resource_timer.start()

    def __exit_action__(self):
        pass

    def __about_action__(self):
        pass

    def __general_command_send_clicked__(self):
        pass

    def __general_controls_start_clicked__(self):
        pass

    def __general_controls_restart_clicked__(self):
        pass

    def __general_controls_stop_clicked__(self):
        pass

    def __update_resource_usage__(self):
        if not self.widgets.tab_widget.isTabVisible(6):
            return
        sb_running = False
        self.widgets.stats.resource_cpu_gui_data.setText(f"{round(psutil.Process().cpu_percent(), 2)}%")
        self.widgets.stats.resource_ram_gui_data.setText(f"{round(psutil.Process().memory_percent(), 2)}%")
        for proc in psutil.process_iter():
            if "starbound_server" in proc.name():
                sb_running = True
                print(proc.pid)
                self.widgets.stats.resource_cpu_server_data.setText(f"{round(proc.cpu_percent() / psutil.cpu_count(), 2)}%")
                self.widgets.stats.resource_ram_server_data.setText(f"{round(proc.memory_percent(), 2)}%")
        if not sb_running:
            self.widgets.stats.resource_cpu_server_data.setText(f"-")
            self.widgets.stats.resource_ram_server_data.setText(f"-")
        self.widgets.stats.resource_cpu_total_data.setText(f"{psutil.cpu_percent()}%")
        self.widgets.stats.resource_ram_total_data.setText(f"{psutil.virtual_memory().percent}%")


def main():
    app = QtW.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    app.exec_()
