import os
import sys
import json

import psutil
from PySide6 import QtWidgets as QtW
from PySide6 import QtGui as QtG
from PySide6 import QtCore as QtC


MonospaceFont = QtG.QFont("monospace")


class Widgets:
    pass


class MainWindow(QtW.QMainWindow):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setWindowTitle("Starbound Server Manager")
        self.setWindowIcon(QtG.QIcon(os.path.join("resources", "images", "ssm-logo.png")))
        self.setMinimumSize(1080, 850)
        self.setFont(MonospaceFont)
        self.widgets = Widgets()

        with open(os.path.join("starbound_server.config")) as file:
            self.config = json.load(file)

        # Menu and Status
        self.top_menu = self.menuBar()
        self.w_file_menu = self.top_menu.addMenu("&File")
        self.w_exit_action = self.w_file_menu.addAction("E&xit")
        self.w_exit_action.triggered.connect(self.__exit_action__)
        self.w_help_menu = self.top_menu.addMenu("&Help")
        self.w_about_action = self.w_help_menu.addAction("&About")
        self.w_about_action.triggered.connect(self.__about_action__)

        self.w_status = self.statusBar()

        # Main Layout
        self.w_central_widget = QtW.QWidget()
        self.w_layout = QtW.QVBoxLayout()
        self.w_central_widget.setLayout(self.w_layout)
        self.setCentralWidget(self.w_central_widget)
        self.w_tab_widget = QtW.QTabWidget()
        self.w_layout.addWidget(self.w_tab_widget)

        # General Tab
        self.w_general_widget = QtW.QWidget()
        self.w_general_layout = QtW.QGridLayout()
        self.w_general_layout.setColumnStretch(1, 1)
        self.w_general_widget.setLayout(self.w_general_layout)
        self.w_tab_widget.addTab(self.w_general_widget, "General")

        self.w_general_player_label = QtW.QLabel("Players")
        self.w_general_layout.addWidget(self.w_general_player_label, 0, 0)
        self.w_general_log_label = QtW.QLabel("Server Log")
        self.w_general_layout.addWidget(self.w_general_log_label, 0, 1)

        self.w_general_player_list = QtW.QListWidget()
        self.w_general_player_list.addItem(QtW.QListWidgetItem(QtG.QIcon(os.path.join("resources", "images", "ssm-logo.png")), "Test Item"))
        self.w_general_layout.addWidget(self.w_general_player_list, 1, 0, 4, 1)

        self.w_general_log_list = QtW.QListWidget()
        self.w_general_log_list.setVerticalScrollBarPolicy(QtC.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.w_general_log_list.addItem("[01:09:35] Server stopped")
        self.w_general_layout.addWidget(self.w_general_log_list, 1, 1)

        self.w_general_command_layout = QtW.QHBoxLayout()
        self.w_general_layout.addLayout(self.w_general_command_layout, 2, 1)
        self.w_general_command_edit = QtW.QLineEdit()
        self.w_general_command_layout.addWidget(self.w_general_command_edit)
        self.w_general_command_send = QtW.QPushButton("Send")
        self.w_general_command_send.clicked.connect(self.__general_command_send_clicked__)
        self.w_general_command_layout.addWidget(self.w_general_command_send)

        self.w_general_chat_label = QtW.QLabel("Chat Log")
        self.w_general_layout.addWidget(self.w_general_chat_label, 3, 1)
        self.w_general_chat_list = QtW.QListWidget()
        self.w_general_chat_list.setVerticalScrollBarPolicy(QtC.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.w_general_layout.addWidget(self.w_general_chat_list, 4, 1)

        self.w_general_controls_group = QtW.QGroupBox("Server Controls")
        self.w_general_layout.addWidget(self.w_general_controls_group, 5, 0)
        self.w_general_controls_layout = QtW.QVBoxLayout()
        self.w_general_controls_group.setLayout(self.w_general_controls_layout)
        self.w_general_controls_start = QtW.QPushButton("Start")
        self.w_general_controls_start.clicked.connect(self.__general_controls_start_clicked__)
        self.w_general_controls_layout.addWidget(self.w_general_controls_start)
        self.w_general_controls_restart = QtW.QPushButton("Restart")
        self.w_general_controls_start.clicked.connect(self.__general_controls_restart_clicked__)
        self.w_general_controls_layout.addWidget(self.w_general_controls_restart)
        self.w_general_controls_stop = QtW.QPushButton("Stop")
        self.w_general_controls_start.clicked.connect(self.__general_controls_stop_clicked__)
        self.w_general_controls_layout.addWidget(self.w_general_controls_stop)

        self.w_general_info_group = QtW.QGroupBox("Information")
        self.w_general_layout.addWidget(self.w_general_info_group, 5, 1)
        self.w_general_info_layout = QtW.QGridLayout()
        self.w_general_info_group.setLayout(self.w_general_info_layout)
        self.w_general_info_status_label = QtW.QLabel("Status:")
        self.w_general_info_layout.addWidget(self.w_general_info_status_label, 0, 0)
        self.w_general_info_status_data = QtW.QLabel("Offline")
        self.w_general_info_layout.addWidget(self.w_general_info_status_data, 0, 1, 1, 3)
        self.w_general_info_uptime_label = QtW.QLabel("Uptime:")
        self.w_general_info_layout.addWidget(self.w_general_info_uptime_label, 1, 0)
        self.w_general_info_uptime_data = QtW.QLabel("0d 0h 0m 0s")
        self.w_general_info_layout.addWidget(self.w_general_info_uptime_data, 1, 1, 1, 3)
        self.w_general_info_version_label = QtW.QLabel("Version:")
        self.w_general_info_layout.addWidget(self.w_general_info_version_label, 2, 0)
        self.w_general_info_version_data = QtW.QLabel("Unknown")
        self.w_general_info_layout.addWidget(self.w_general_info_version_data, 2, 1, 1, 3)
        self.w_general_info_ip_label = QtW.QLabel("IP:")
        self.w_general_info_layout.addWidget(self.w_general_info_ip_label, 3, 0)
        self.w_general_info_ip_data = QtW.QLabel("0.0.0.0")
        self.w_general_info_layout.addWidget(self.w_general_info_ip_data, 3, 1)
        self.w_general_info_port_label = QtW.QLabel("Port:")
        self.w_general_info_layout.addWidget(self.w_general_info_port_label, 3, 2)
        self.w_general_info_port_data = QtW.QLabel("21025")
        self.w_general_info_layout.addWidget(self.w_general_info_port_data, 3, 3)
        self.w_general_info_connected_label = QtW.QLabel("Players Connected:")
        self.w_general_info_layout.addWidget(self.w_general_info_connected_label, 0, 4)
        self.w_general_info_connected_data = QtW.QLabel("0")
        self.w_general_info_layout.addWidget(self.w_general_info_connected_data, 0, 5)
        self.w_general_info_planets_label = QtW.QLabel("Loaded Planets:")
        self.w_general_info_layout.addWidget(self.w_general_info_planets_label, 1, 4)
        self.w_general_info_planets_data = QtW.QLabel("0")
        self.w_general_info_layout.addWidget(self.w_general_info_planets_data, 1, 5)
        self.w_general_info_ships_label = QtW.QLabel("Loaded Ships:")
        self.w_general_info_layout.addWidget(self.w_general_info_ships_label, 2, 4)
        self.w_general_info_ships_data = QtW.QLabel("0")
        self.w_general_info_layout.addWidget(self.w_general_info_ships_data, 2, 5)
        self.w_general_info_layout.setColumnStretch(1, 1)
        self.w_general_info_layout.setColumnStretch(3, 1)
        self.w_general_info_layout.setColumnStretch(5, 1)

        # Players Tab
        self.w_players_widget = QtW.QWidget()
        self.w_players_layout = QtW.QVBoxLayout()
        self.w_players_widget.setLayout(self.w_players_layout)
        self.w_tab_widget.addTab(self.w_players_widget, "Players")

        self.w_players_current_players_layout = QtW.QHBoxLayout()
        self.w_players_layout.addLayout(self.w_players_current_players_layout)
        self.w_players_current_players_label = QtW.QLabel("Current Connected Players:")
        self.w_players_current_players_layout.addWidget(self.w_players_current_players_label)
        self.w_players_current_players_data = QtW.QLabel("0")
        self.w_players_current_players_layout.addWidget(self.w_players_current_players_data, 1)
        self.w_players_current_players_table = QtW.QTableWidget()
        self.w_players_current_players_table.setColumnCount(6)
        self.w_players_current_players_table.verticalHeader().setVisible(False)
        self.w_players_current_players_table.setHorizontalHeaderLabels(("ID", "Name", "Account", "UUID", "IP", "Connection Time"))
        self.w_players_current_players_table.horizontalHeader().setSectionResizeMode(QtW.QHeaderView.ResizeMode.Stretch)
        self.w_players_current_players_table.horizontalHeader().setSectionResizeMode(0, QtW.QHeaderView.ResizeMode.ResizeToContents)
        self.w_players_layout.addWidget(self.w_players_current_players_table)

        self.w_players_recent_players_layout = QtW.QHBoxLayout()
        self.w_players_layout.addLayout(self.w_players_recent_players_layout)
        self.w_players_recent_players_label = QtW.QLabel("Recent Connected Players:")
        self.w_players_recent_players_layout.addWidget(self.w_players_recent_players_label)
        self.w_players_recent_players_data = QtW.QLabel("0")
        self.w_players_recent_players_layout.addWidget(self.w_players_recent_players_data, 1)
        self.w_players_recent_players_table = QtW.QTableWidget()
        self.w_players_recent_players_table.setColumnCount(6)
        self.w_players_recent_players_table.verticalHeader().setVisible(False)
        self.w_players_recent_players_table.setHorizontalHeaderLabels(("Name", "Account", "UUID", "IP", "Last Connection", "Last Disconnect"))
        self.w_players_recent_players_table.horizontalHeader().setSectionResizeMode(QtW.QHeaderView.ResizeMode.Stretch)
        self.w_players_layout.addWidget(self.w_players_recent_players_table)

        # Universe Tab
        self.w_universe_widget = QtW.QWidget()
        self.w_universe_layout = QtW.QVBoxLayout()
        self.w_universe_widget.setLayout(self.w_universe_layout)
        self.w_tab_widget.addTab(self.w_universe_widget, "Universe")

        self.w_universe_current_planets_layout = QtW.QHBoxLayout()
        self.w_universe_layout.addLayout(self.w_universe_current_planets_layout)
        self.w_universe_current_planets_label = QtW.QLabel("Current Loaded Planets:")
        self.w_universe_current_planets_layout.addWidget(self.w_universe_current_planets_label)
        self.w_universe_current_planets_data = QtW.QLabel("0")
        self.w_universe_current_planets_layout.addWidget(self.w_universe_current_planets_data, 1)
        self.w_universe_current_planets_table = QtW.QTableWidget()
        self.w_universe_current_planets_table.setColumnCount(8)
        self.w_universe_current_planets_table.verticalHeader().setVisible(False)
        self.w_universe_current_planets_table.setHorizontalHeaderLabels(("Type", "X", "Y", "System", "Orbital", "Letter", "Time Loaded", "Nickname"))
        self.w_universe_current_planets_table.horizontalHeader().setSectionResizeMode(QtW.QHeaderView.ResizeMode.Stretch)
        self.w_universe_current_planets_table.horizontalHeader().setSectionResizeMode(0, QtW.QHeaderView.ResizeMode.ResizeToContents)
        self.w_universe_current_planets_table.horizontalHeader().setSectionResizeMode(4, QtW.QHeaderView.ResizeMode.ResizeToContents)
        self.w_universe_current_planets_table.horizontalHeader().setSectionResizeMode(5, QtW.QHeaderView.ResizeMode.ResizeToContents)
        self.w_universe_layout.addWidget(self.w_universe_current_planets_table)

        self.w_universe_recent_planets_layout = QtW.QHBoxLayout()
        self.w_universe_layout.addLayout(self.w_universe_recent_planets_layout)
        self.w_universe_recent_planets_label = QtW.QLabel("Recent Loaded Planets:")
        self.w_universe_recent_planets_layout.addWidget(self.w_universe_recent_planets_label)
        self.w_universe_recent_planets_data = QtW.QLabel("0")
        self.w_universe_recent_planets_layout.addWidget(self.w_universe_recent_planets_data, 1)
        self.w_universe_recent_planets_table = QtW.QTableWidget()
        self.w_universe_recent_planets_table.setColumnCount(8)
        self.w_universe_recent_planets_table.verticalHeader().setVisible(False)
        self.w_universe_recent_planets_table.setHorizontalHeaderLabels(("Type", "X", "Y", "System", "Orbital", "Letter", "Time Loaded", "Nickname"))
        self.w_universe_recent_planets_table.horizontalHeader().setSectionResizeMode(QtW.QHeaderView.ResizeMode.Stretch)
        self.w_universe_recent_planets_table.horizontalHeader().setSectionResizeMode(0, QtW.QHeaderView.ResizeMode.ResizeToContents)
        self.w_universe_recent_planets_table.horizontalHeader().setSectionResizeMode(4, QtW.QHeaderView.ResizeMode.ResizeToContents)
        self.w_universe_recent_planets_table.horizontalHeader().setSectionResizeMode(5, QtW.QHeaderView.ResizeMode.ResizeToContents)
        self.w_universe_layout.addWidget(self.w_universe_recent_planets_table)

        # Ships Tab
        self.w_ships_widget = QtW.QWidget()
        self.w_ships_layout = QtW.QVBoxLayout()
        self.w_ships_widget.setLayout(self.w_ships_layout)
        self.w_tab_widget.addTab(self.w_ships_widget, "Ships")

        self.w_ships_current_ships_layout = QtW.QHBoxLayout()
        self.w_ships_layout.addLayout(self.w_ships_current_ships_layout)
        self.w_ships_current_ships_label = QtW.QLabel("Current Ships:")
        self.w_ships_current_ships_layout.addWidget(self.w_ships_current_ships_label)
        self.w_ships_current_ships_data = QtW.QLabel("0")
        self.w_ships_current_ships_layout.addWidget(self.w_ships_current_ships_data, 1)
        self.w_ships_current_ships_table = QtW.QTableWidget()
        self.w_ships_current_ships_table.setColumnCount(7)
        self.w_ships_current_ships_table.verticalHeader().setVisible(False)
        self.w_ships_current_ships_table.setHorizontalHeaderLabels(("Player", "X", "Y", "System", "Orbital", "Letter", "Time Loaded"))
        self.w_ships_current_ships_table.horizontalHeader().setSectionResizeMode(QtW.QHeaderView.ResizeMode.Stretch)
        self.w_ships_layout.addWidget(self.w_ships_current_ships_table)

        self.w_ships_recent_ships_layout = QtW.QHBoxLayout()
        self.w_ships_layout.addLayout(self.w_ships_recent_ships_layout)
        self.w_ships_recent_ships_label = QtW.QLabel("Recent Ships:")
        self.w_ships_recent_ships_layout.addWidget(self.w_ships_recent_ships_label)
        self.w_ships_recent_ships_data = QtW.QLabel("0")
        self.w_ships_recent_ships_layout.addWidget(self.w_ships_recent_ships_data, 1)
        self.w_ships_recent_ships_table = QtW.QTableWidget()
        self.w_ships_recent_ships_table.setColumnCount(8)
        self.w_ships_recent_ships_table.verticalHeader().setVisible(False)
        self.w_ships_recent_ships_table.setHorizontalHeaderLabels(("Player", "X", "Y", "System", "Orbital", "Letter", "Time Loaded", "Time Unloaded"))
        self.w_ships_recent_ships_table.horizontalHeader().setSectionResizeMode(QtW.QHeaderView.ResizeMode.Stretch)
        self.w_ships_layout.addWidget(self.w_ships_recent_ships_table)

        # Player Tracking
        self.w_tracking_widget = QtW.QWidget()
        self.w_tracking_layout = QtW.QVBoxLayout()
        self.w_tracking_widget.setLayout(self.w_tracking_layout)
        self.w_tab_widget.addTab(self.w_tracking_widget, "Tracking")

        self.w_tracking_player_tracking_label = QtW.QLabel("Tracking")

        # Events Log
        self.w_events_widget = QtW.QWidget()
        self.w_events_layout = QtW.QVBoxLayout()
        self.w_events_widget.setLayout(self.w_events_layout)
        self.w_tab_widget.addTab(self.w_events_widget, "Events")

        # Statistics
        self.w_stats_widget = QtW.QWidget()
        self.w_stats_layout = QtW.QGridLayout()
        self.w_stats_widget.setLayout(self.w_stats_layout)
        self.w_tab_widget.addTab(self.w_stats_widget, "Statistics")

        self.w_stats_current_stats_group = QtW.QGroupBox("Currently:")
        self.w_stats_layout.addWidget(self.w_stats_current_stats_group, 0, 0)
        self.w_stats_current_stats_layout = QtW.QGridLayout()
        self.w_stats_current_stats_layout.setColumnStretch(1, 1)
        self.w_stats_current_stats_group.setLayout(self.w_stats_current_stats_layout)
        self.w_stats_current_stats_players_label = QtW.QLabel("Players:")
        self.w_stats_current_stats_layout.addWidget(self.w_stats_current_stats_players_label, 0, 0)
        self.w_stats_current_stats_players_data = QtW.QLabel("0")
        self.w_stats_current_stats_players_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_current_stats_layout.addWidget(self.w_stats_current_stats_players_data, 0, 1)
        self.w_stats_current_stats_planets_label = QtW.QLabel("Planets:")
        self.w_stats_current_stats_layout.addWidget(self.w_stats_current_stats_planets_label, 1, 0)
        self.w_stats_current_stats_planets_data = QtW.QLabel("0")
        self.w_stats_current_stats_planets_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_current_stats_layout.addWidget(self.w_stats_current_stats_planets_data, 1, 1)
        self.w_stats_current_stats_ships_label = QtW.QLabel("Ships:")
        self.w_stats_current_stats_layout.addWidget(self.w_stats_current_stats_ships_label, 2, 0)
        self.w_stats_current_stats_ships_data = QtW.QLabel("0")
        self.w_stats_current_stats_ships_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_current_stats_layout.addWidget(self.w_stats_current_stats_ships_data, 2, 1)
        self.w_stats_current_stats_layout.setRowStretch(3, 1)

        self.w_stats_current_session_group = QtW.QGroupBox("Current Session:")
        self.w_stats_layout.addWidget(self.w_stats_current_session_group, 0, 1)
        self.w_stats_current_session_layout = QtW.QGridLayout()
        self.w_stats_current_session_layout.setColumnStretch(1, 1)
        self.w_stats_current_session_group.setLayout(self.w_stats_current_session_layout)
        self.w_stats_current_session_players_login_label = QtW.QLabel("Players Login:")
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_players_login_label, 0, 0)
        self.w_stats_current_session_players_login_data = QtW.QLabel("0")
        self.w_stats_current_session_players_login_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_players_login_data, 0, 1)
        self.w_stats_current_session_players_logout_label = QtW.QLabel("Players Logout:")
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_players_logout_label, 1, 0)
        self.w_stats_current_session_players_logout_data = QtW.QLabel("0")
        self.w_stats_current_session_players_logout_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_players_logout_data, 1, 1)
        self.w_stats_current_session_layout.addWidget(QtW.QLabel(), 2, 0)
        self.w_stats_current_session_planet_loaded_label = QtW.QLabel("Planets Loaded:")
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_planet_loaded_label, 3, 0)
        self.w_stats_current_session_planet_loaded_data = QtW.QLabel("0")
        self.w_stats_current_session_planet_loaded_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_planet_loaded_data, 3, 1)
        self.w_stats_current_session_planet_unloaded_label = QtW.QLabel("Planets Unloaded:")
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_planet_unloaded_label, 4, 0)
        self.w_stats_current_session_planet_unloaded_data = QtW.QLabel("0")
        self.w_stats_current_session_planet_unloaded_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_planet_unloaded_data, 4, 1)
        self.w_stats_current_session_layout.addWidget(QtW.QLabel(), 5, 0)
        self.w_stats_current_session_ships_loaded_label = QtW.QLabel("Ships Loaded:")
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_ships_loaded_label, 6, 0)
        self.w_stats_current_session_ships_loaded_data = QtW.QLabel("0")
        self.w_stats_current_session_ships_loaded_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_ships_loaded_data, 6, 1)
        self.w_stats_current_session_ships_unloaded_label = QtW.QLabel("Ships Unloaded:")
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_ships_unloaded_label, 7, 0)
        self.w_stats_current_session_ships_unloaded_data = QtW.QLabel("0")
        self.w_stats_current_session_ships_unloaded_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_ships_unloaded_data, 7, 1)
        self.w_stats_current_session_layout.addWidget(QtW.QLabel(), 8, 0)
        self.w_stats_current_session_players_warped_label = QtW.QLabel("Players Warped:")
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_players_warped_label, 9, 0)
        self.w_stats_current_session_players_warped_data = QtW.QLabel("0")
        self.w_stats_current_session_players_warped_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_players_warped_data, 9, 1)
        self.w_stats_current_session_ships_travel_label = QtW.QLabel("Ships Traveled:")
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_ships_travel_label, 10, 0)
        self.w_stats_current_session_ships_travel_data = QtW.QLabel("0")
        self.w_stats_current_session_ships_travel_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_ships_travel_data, 10, 1)
        self.w_stats_current_session_layout.addWidget(QtW.QLabel(), 11, 0)
        self.w_stats_current_session_server_events_label = QtW.QLabel("Server Events:")
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_server_events_label, 12, 0)
        self.w_stats_current_session_server_events_data = QtW.QLabel("0")
        self.w_stats_current_session_server_events_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_server_events_data, 12, 1)
        self.w_stats_current_session_events_label = QtW.QLabel("Events:")
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_events_label, 13, 0)
        self.w_stats_current_session_events_data = QtW.QLabel("0")
        self.w_stats_current_session_events_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_events_data, 13, 1)
        self.w_stats_current_session_layout.addWidget(QtW.QLabel(), 14, 0)
        self.w_stats_current_session_chat_entries_label = QtW.QLabel("Chat Entries:")
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_chat_entries_label, 15, 0)
        self.w_stats_current_session_chat_entries_data = QtW.QLabel("0")
        self.w_stats_current_session_chat_entries_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_chat_entries_data, 15, 1)
        self.w_stats_current_session_layout.addWidget(QtW.QLabel(), 16, 0)
        self.w_stats_current_session_up_time_label = QtW.QLabel("Up Time:")
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_up_time_label, 17, 0)
        self.w_stats_current_session_up_time_data = QtW.QLabel("0d 0h 0m 0s")
        self.w_stats_current_session_up_time_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_current_session_layout.addWidget(self.w_stats_current_session_up_time_data, 17, 1)
        self.w_stats_current_session_layout.setRowStretch(18, 1)

        self.w_stats_past_session_group = QtW.QGroupBox("Past Session:")
        self.w_stats_layout.addWidget(self.w_stats_past_session_group, 0, 2)
        self.w_stats_past_session_layout = QtW.QGridLayout()
        self.w_stats_past_session_layout.setColumnStretch(1, 1)
        self.w_stats_past_session_group.setLayout(self.w_stats_past_session_layout)
        self.w_stats_past_session_players_login_label = QtW.QLabel("Players Login:")
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_players_login_label, 0, 0)
        self.w_stats_past_session_players_login_data = QtW.QLabel("0")
        self.w_stats_past_session_players_login_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_players_login_data, 0, 1)
        self.w_stats_past_session_players_logout_label = QtW.QLabel("Players Logout:")
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_players_logout_label, 1, 0)
        self.w_stats_past_session_players_logout_data = QtW.QLabel("0")
        self.w_stats_past_session_players_logout_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_players_logout_data, 1, 1)
        self.w_stats_past_session_layout.addWidget(QtW.QLabel(), 2, 0)
        self.w_stats_past_session_planet_loaded_label = QtW.QLabel("Planets Loaded:")
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_planet_loaded_label, 3, 0)
        self.w_stats_past_session_planet_loaded_data = QtW.QLabel("0")
        self.w_stats_past_session_planet_loaded_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_planet_loaded_data, 3, 1)
        self.w_stats_past_session_planet_unloaded_label = QtW.QLabel("Planets Unloaded:")
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_planet_unloaded_label, 4, 0)
        self.w_stats_past_session_planet_unloaded_data = QtW.QLabel("0")
        self.w_stats_past_session_planet_unloaded_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_planet_unloaded_data, 4, 1)
        self.w_stats_past_session_layout.addWidget(QtW.QLabel(), 5, 0)
        self.w_stats_past_session_ships_loaded_label = QtW.QLabel("Ships Loaded:")
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_ships_loaded_label, 6, 0)
        self.w_stats_past_session_ships_loaded_data = QtW.QLabel("0")
        self.w_stats_past_session_ships_loaded_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_ships_loaded_data, 6, 1)
        self.w_stats_past_session_ships_unloaded_label = QtW.QLabel("Ships Unloaded:")
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_ships_unloaded_label, 7, 0)
        self.w_stats_past_session_ships_unloaded_data = QtW.QLabel("0")
        self.w_stats_past_session_ships_unloaded_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_ships_unloaded_data, 7, 1)
        self.w_stats_past_session_layout.addWidget(QtW.QLabel(), 8, 0)
        self.w_stats_past_session_players_warped_label = QtW.QLabel("Players Warped:")
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_players_warped_label, 9, 0)
        self.w_stats_past_session_players_warped_data = QtW.QLabel("0")
        self.w_stats_past_session_players_warped_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_players_warped_data, 9, 1)
        self.w_stats_past_session_ships_travel_label = QtW.QLabel("Ships Traveled:")
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_ships_travel_label, 10, 0)
        self.w_stats_past_session_ships_travel_data = QtW.QLabel("0")
        self.w_stats_past_session_ships_travel_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_ships_travel_data, 10, 1)
        self.w_stats_past_session_layout.addWidget(QtW.QLabel(), 11, 0)
        self.w_stats_past_session_server_events_label = QtW.QLabel("Server Events:")
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_server_events_label, 12, 0)
        self.w_stats_past_session_server_events_data = QtW.QLabel("0")
        self.w_stats_past_session_server_events_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_server_events_data, 12, 1)
        self.w_stats_past_session_events_label = QtW.QLabel("Events:")
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_events_label, 13, 0)
        self.w_stats_past_session_events_data = QtW.QLabel("0")
        self.w_stats_past_session_events_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_events_data, 13, 1)
        self.w_stats_past_session_layout.addWidget(QtW.QLabel(), 14, 0)
        self.w_stats_past_session_chat_entries_label = QtW.QLabel("Chat Entries:")
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_chat_entries_label, 15, 0)
        self.w_stats_past_session_chat_entries_data = QtW.QLabel("0")
        self.w_stats_past_session_chat_entries_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_chat_entries_data, 15, 1)
        self.w_stats_past_session_layout.addWidget(QtW.QLabel(), 16, 0)
        self.w_stats_past_session_up_time_label = QtW.QLabel("Up Time:")
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_up_time_label, 17, 0)
        self.w_stats_past_session_up_time_data = QtW.QLabel("0d 0h 0m 0s")
        self.w_stats_past_session_up_time_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_past_session_layout.addWidget(self.w_stats_past_session_up_time_data, 17, 1)
        self.w_stats_past_session_layout.setRowStretch(18, 1)

        self.w_stats_overall_group = QtW.QGroupBox("Overall:")
        self.w_stats_layout.addWidget(self.w_stats_overall_group, 0, 3)
        self.w_stats_overall_layout = QtW.QGridLayout()
        self.w_stats_overall_layout.setColumnStretch(1, 1)
        self.w_stats_overall_group.setLayout(self.w_stats_overall_layout)
        self.w_stats_overall_players_login_label = QtW.QLabel("Players Login:")
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_players_login_label, 0, 0)
        self.w_stats_overall_players_login_data = QtW.QLabel("0")
        self.w_stats_overall_players_login_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_players_login_data, 0, 1)
        self.w_stats_overall_players_logout_label = QtW.QLabel("Players Logout:")
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_players_logout_label, 1, 0)
        self.w_stats_overall_players_logout_data = QtW.QLabel("0")
        self.w_stats_overall_players_logout_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_players_logout_data, 1, 1)
        self.w_stats_overall_layout.addWidget(QtW.QLabel(), 2, 0)
        self.w_stats_overall_planet_loaded_label = QtW.QLabel("Planets Loaded:")
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_planet_loaded_label, 3, 0)
        self.w_stats_overall_planet_loaded_data = QtW.QLabel("0")
        self.w_stats_overall_planet_loaded_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_planet_loaded_data, 3, 1)
        self.w_stats_overall_planet_unloaded_label = QtW.QLabel("Planets Unloaded:")
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_planet_unloaded_label, 4, 0)
        self.w_stats_overall_planet_unloaded_data = QtW.QLabel("0")
        self.w_stats_overall_planet_unloaded_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_planet_unloaded_data, 4, 1)
        self.w_stats_overall_layout.addWidget(QtW.QLabel(), 5, 0)
        self.w_stats_overall_ships_loaded_label = QtW.QLabel("Ships Loaded:")
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_ships_loaded_label, 6, 0)
        self.w_stats_overall_ships_loaded_data = QtW.QLabel("0")
        self.w_stats_overall_ships_loaded_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_ships_loaded_data, 6, 1)
        self.w_stats_overall_ships_unloaded_label = QtW.QLabel("Ships Unloaded:")
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_ships_unloaded_label, 7, 0)
        self.w_stats_overall_ships_unloaded_data = QtW.QLabel("0")
        self.w_stats_overall_ships_unloaded_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_ships_unloaded_data, 7, 1)
        self.w_stats_overall_layout.addWidget(QtW.QLabel(), 8, 0)
        self.w_stats_overall_players_warped_label = QtW.QLabel("Players Warped:")
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_players_warped_label, 9, 0)
        self.w_stats_overall_players_warped_data = QtW.QLabel("0")
        self.w_stats_overall_players_warped_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_players_warped_data, 9, 1)
        self.w_stats_overall_ships_travel_label = QtW.QLabel("Ships Traveled:")
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_ships_travel_label, 10, 0)
        self.w_stats_overall_ships_travel_data = QtW.QLabel("0")
        self.w_stats_overall_ships_travel_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_ships_travel_data, 10, 1)
        self.w_stats_overall_layout.addWidget(QtW.QLabel(), 11, 0)
        self.w_stats_overall_server_events_label = QtW.QLabel("Server Events:")
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_server_events_label, 12, 0)
        self.w_stats_overall_server_events_data = QtW.QLabel("0")
        self.w_stats_overall_server_events_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_server_events_data, 12, 1)
        self.w_stats_overall_events_label = QtW.QLabel("Events:")
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_events_label, 13, 0)
        self.w_stats_overall_events_data = QtW.QLabel("0")
        self.w_stats_overall_events_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_events_data, 13, 1)
        self.w_stats_overall_layout.addWidget(QtW.QLabel(), 14, 0)
        self.w_stats_overall_chat_entries_label = QtW.QLabel("Chat Entries:")
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_chat_entries_label, 15, 0)
        self.w_stats_overall_chat_entries_data = QtW.QLabel("0")
        self.w_stats_overall_chat_entries_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_chat_entries_data, 15, 1)
        self.w_stats_overall_layout.addWidget(QtW.QLabel(), 16, 0)
        self.w_stats_overall_up_time_label = QtW.QLabel("Up Time:")
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_up_time_label, 17, 0)
        self.w_stats_overall_up_time_data = QtW.QLabel("0d 0h 0m 0s")
        self.w_stats_overall_up_time_data.setAlignment(QtC.Qt.AlignmentFlag.AlignRight)
        self.w_stats_overall_layout.addWidget(self.w_stats_overall_up_time_data, 17, 1)
        self.w_stats_overall_layout.setRowStretch(18, 1)

        self.w_stats_resource_group = QtW.QGroupBox("Resource Usage:")
        self.w_stats_layout.addWidget(self.w_stats_resource_group, 1, 0, 1, 2)
        self.w_stats_resource_layout = QtW.QGridLayout()
        self.w_stats_resource_layout.setColumnStretch(1, 1)
        self.w_stats_resource_layout.setColumnStretch(3, 1)
        self.w_stats_resource_group.setLayout(self.w_stats_resource_layout)
        self.w_stats_resource_cpu_label = QtW.QLabel("CPU Usage:")
        self.w_stats_resource_layout.addWidget(self.w_stats_resource_cpu_label, 0, 0, 1, 2)
        self.w_stats_resource_cpu_gui_label = QtW.QLabel("SSM:")
        self.w_stats_resource_layout.addWidget(self.w_stats_resource_cpu_gui_label, 1, 0)
        self.w_stats_resource_cpu_gui_data = QtW.QLabel("0%")
        self.w_stats_resource_layout.addWidget(self.w_stats_resource_cpu_gui_data, 1, 1)
        self.w_stats_resource_cpu_server_label = QtW.QLabel("Server:")
        self.w_stats_resource_layout.addWidget(self.w_stats_resource_cpu_server_label, 2, 0)
        self.w_stats_resource_cpu_server_data = QtW.QLabel("0%")
        self.w_stats_resource_layout.addWidget(self.w_stats_resource_cpu_server_data, 2, 1)
        self.w_stats_resource_cpu_total_label = QtW.QLabel("Total:")
        self.w_stats_resource_layout.addWidget(self.w_stats_resource_cpu_total_label, 3, 0)
        self.w_stats_resource_cpu_total_data = QtW.QLabel("0%")
        self.w_stats_resource_layout.addWidget(self.w_stats_resource_cpu_total_data, 3, 1)
        self.w_stats_resource_ram_label = QtW.QLabel("RAM Usage:")
        self.w_stats_resource_layout.addWidget(self.w_stats_resource_ram_label, 0, 2, 1, 2)
        self.w_stats_resource_ram_gui_label = QtW.QLabel("SSM:")
        self.w_stats_resource_layout.addWidget(self.w_stats_resource_ram_gui_label, 1, 2)
        self.w_stats_resource_ram_gui_data = QtW.QLabel("0%")
        self.w_stats_resource_layout.addWidget(self.w_stats_resource_ram_gui_data, 1, 3)
        self.w_stats_resource_ram_server_label = QtW.QLabel("Server:")
        self.w_stats_resource_layout.addWidget(self.w_stats_resource_ram_server_label, 2, 2)
        self.w_stats_resource_ram_server_data = QtW.QLabel("0%")
        self.w_stats_resource_layout.addWidget(self.w_stats_resource_ram_server_data, 2, 3)
        self.w_stats_resource_ram_total_label = QtW.QLabel("Total:")
        self.w_stats_resource_layout.addWidget(self.w_stats_resource_ram_total_label, 3, 2)
        self.w_stats_resource_ram_total_data = QtW.QLabel("0%")
        self.w_stats_resource_layout.addWidget(self.w_stats_resource_ram_total_data, 3, 3)

        self.w_stats_layout.setRowStretch(2, 1)

        # Server Config Tab
        self.w_config_widget = QtW.QWidget()
        self.w_config_layout = QtW.QGridLayout()
        self.w_config_widget.setLayout(self.w_config_layout)
        self.w_tab_widget.addTab(self.w_config_widget, "Server Config")

        self.w_config_general_group = QtW.QGroupBox("General")
        self.w_config_layout.addWidget(self.w_config_general_group, 0, 0, 1, 3)
        self.w_config_general_layout = QtW.QGridLayout()
        self.w_config_general_layout.setHorizontalSpacing(15)
        self.w_config_general_group.setLayout(self.w_config_general_layout)
        self.w_config_general_server_name_label = QtW.QLabel("Server Name:")
        self.w_config_general_layout.addWidget(self.w_config_general_server_name_label, 0, 0, 1, 3)
        self.w_config_general_server_name_edit = QtW.QLineEdit()
        self.w_config_general_server_name_edit.setText(self.config["serverName"])
        self.w_config_general_server_name_edit.textEdited.connect(self.__server_name_edited__)
        self.w_config_general_layout.addWidget(self.w_config_general_server_name_edit, 1, 0, 1, 3)
        self.w_config_general_server_motd_label = QtW.QLabel("Server MOTD:")
        self.w_config_general_layout.addWidget(self.w_config_general_server_motd_label, 0, 3, 1, 2)
        self.w_config_general_server_motd_edit = QtW.QLineEdit()
        self.w_config_general_layout.addWidget(self.w_config_general_server_motd_edit, 1, 3, 1, 2)
        self.w_config_general_server_port_label = QtW.QLabel("Server Port:")
        self.w_config_general_layout.addWidget(self.w_config_general_server_port_label, 2, 0)
        self.w_config_general_server_port_edit = QtW.QSpinBox()
        self.w_config_general_server_port_edit.setMaximum(65536)
        self.w_config_general_server_port_edit.setValue(self.config["queryServerPort"])
        self.w_config_general_server_port_edit.valueChanged.connect(self.__server_port_edited__)
        self.w_config_general_layout.addWidget(self.w_config_general_server_port_edit, 3, 0)
        self.w_config_general_max_players_label = QtW.QLabel("Max Players:")
        self.w_config_general_layout.addWidget(self.w_config_general_max_players_label, 2, 1)
        self.w_config_general_max_players_edit = QtW.QSpinBox()
        self.w_config_general_max_players_edit.setValue(self.config["maxPlayers"])
        self.w_config_general_max_players_edit.valueChanged.connect(self.__max_players_edited__)
        self.w_config_general_layout.addWidget(self.w_config_general_max_players_edit, 3, 1)
        self.w_config_general_team_size_label = QtW.QLabel("Team Size:")
        self.w_config_general_layout.addWidget(self.w_config_general_team_size_label, 2, 2)
        self.w_config_general_team_size_edit = QtW.QSpinBox()
        self.w_config_general_team_size_edit.setValue(self.config["maxTeamSize"])
        self.w_config_general_team_size_edit.valueChanged.connect(self.__team_size_edited__)
        self.w_config_general_layout.addWidget(self.w_config_general_team_size_edit, 3, 2)
        self.w_config_general_network_bind_label = QtW.QLabel("Network Bind:")
        self.w_config_general_layout.addWidget(self.w_config_general_network_bind_label, 2, 3, 1, 2)
        self.w_config_general_network_button_group = QtW.QButtonGroup()
        self.w_config_general_network_bind_radio_ipv4 = QtW.QRadioButton("IPv4 (Recommended)")
        self.w_config_general_network_button_group.addButton(self.w_config_general_network_bind_radio_ipv4, 1)
        self.w_config_general_layout.addWidget(self.w_config_general_network_bind_radio_ipv4, 3, 3)
        self.w_config_general_network_bind_radio_ipv6 = QtW.QRadioButton("IPv6")
        self.w_config_general_network_button_group.addButton(self.w_config_general_network_bind_radio_ipv6, 2)
        self.w_config_general_layout.addWidget(self.w_config_general_network_bind_radio_ipv6, 3, 4)
        self.w_config_general_layout.setColumnStretch(4, 1)

        self.w_config_permissions_group = QtW.QGroupBox("Permissions")
        self.w_config_layout.addWidget(self.w_config_permissions_group, 1, 0, 1, 3)
        self.w_config_permissions_layout = QtW.QGridLayout()
        self.w_config_permissions_layout.setHorizontalSpacing(15)
        self.w_config_permissions_group.setLayout(self.w_config_permissions_layout)
        self.w_config_permissions_layout.setColumnStretch(1, 1)
        self.w_config_permissions_anonymous_connections_checkbox = QtW.QCheckBox("Allow Anonymous Connections")
        self.w_config_permissions_layout.addWidget(self.w_config_permissions_anonymous_connections_checkbox, 0, 0)
        self.w_config_permissions_anonymous_admin_checkbox = QtW.QCheckBox("Anonymous Connections are Admin")
        self.w_config_permissions_layout.addWidget(self.w_config_permissions_anonymous_admin_checkbox, 0, 1)
        self.w_config_permissions_allow_admin_checkbox = QtW.QCheckBox("Allow Admin Commands")
        self.w_config_permissions_layout.addWidget(self.w_config_permissions_allow_admin_checkbox, 1, 0)
        self.w_config_permissions_allow_admin_all_checkbox = QtW.QCheckBox("Allow Admin Commands from Anyone")
        self.w_config_permissions_layout.addWidget(self.w_config_permissions_allow_admin_all_checkbox, 1, 1)

        self.w_config_rcon_group = QtW.QGroupBox("RCON")
        self.w_config_layout.addWidget(self.w_config_rcon_group, 2, 0, 1, 3)
        self.w_config_rcon_layout = QtW.QGridLayout()
        self.w_config_rcon_layout.setHorizontalSpacing(15)
        self.w_config_rcon_group.setLayout(self.w_config_rcon_layout)
        self.w_config_rcon_layout.setColumnStretch(0, 2)
        self.w_config_rcon_layout.setColumnStretch(1, 2)
        self.w_config_rcon_layout.setColumnStretch(2, 1)
        self.w_config_rcon_layout.setColumnStretch(3, 1)
        self.w_config_rcon_layout.setColumnStretch(4, 3)
        self.w_config_rcon_ip_label = QtW.QLabel("IP Address:")
        self.w_config_rcon_layout.addWidget(self.w_config_rcon_ip_label, 0, 0)
        self.w_config_rcon_password_label = QtW.QLabel("Password:")
        self.w_config_rcon_layout.addWidget(self.w_config_rcon_password_label, 0, 1)
        self.w_config_rcon_port_label = QtW.QLabel("Port:")
        self.w_config_rcon_layout.addWidget(self.w_config_rcon_port_label, 0, 2)
        self.w_config_rcon_timeout_label = QtW.QLabel("Timeout:")
        self.w_config_rcon_layout.addWidget(self.w_config_rcon_timeout_label, 0, 3)
        self.w_config_rcon_ip_edit = QtW.QLineEdit()
        self.w_config_rcon_layout.addWidget(self.w_config_rcon_ip_edit, 1, 0)
        self.w_config_rcon_password_edit = QtW.QLineEdit()
        self.w_config_rcon_layout.addWidget(self.w_config_rcon_password_edit, 1, 1)
        self.w_config_rcon_port_edit = QtW.QSpinBox()
        self.w_config_rcon_layout.addWidget(self.w_config_rcon_port_edit, 1, 2)
        self.w_config_rcon_timeout_edit = QtW.QSpinBox()
        self.w_config_rcon_layout.addWidget(self.w_config_rcon_timeout_edit, 1, 3)
        self.w_config_rcon_enable_checkbox = QtW.QCheckBox("Enable RCON")
        self.w_config_rcon_layout.addWidget(self.w_config_rcon_enable_checkbox, 1, 4)

        self.w_config_accounts_group = QtW.QGroupBox("Accounts")
        self.w_config_layout.addWidget(self.w_config_accounts_group, 3, 0)
        self.w_config_accounts_layout = QtW.QGridLayout()
        self.w_config_accounts_group.setLayout(self.w_config_accounts_layout)
        self.w_config_accounts_table = QtW.QTableWidget()
        self.w_config_accounts_table.setColumnCount(3)
        self.w_config_accounts_table.verticalHeader().setVisible(False)
        self.w_config_accounts_table.setHorizontalHeaderLabels(("Account Name", "Password", "Admin"))
        self.w_config_accounts_table.horizontalHeader().setSectionResizeMode(0, QtW.QHeaderView.ResizeMode.Stretch)
        self.w_config_accounts_table.horizontalHeader().setSectionResizeMode(1, QtW.QHeaderView.ResizeMode.Stretch)
        self.w_config_accounts_table.horizontalHeader().setSectionResizeMode(2, QtW.QHeaderView.ResizeMode.ResizeToContents)
        self.w_config_accounts_layout.addWidget(self.w_config_accounts_table, 0, 0, 1, 3)
        self.w_config_accounts_name_label = QtW.QLabel("Account Name:")
        self.w_config_accounts_layout.addWidget(self.w_config_accounts_name_label, 1, 0)
        self.w_config_accounts_name_edit = QtW.QLineEdit()
        self.w_config_accounts_layout.addWidget(self.w_config_accounts_name_edit, 1, 1)
        self.w_config_accounts_admin_checkbox = QtW.QCheckBox("Admin")
        self.w_config_accounts_layout.addWidget(self.w_config_accounts_admin_checkbox, 1, 2)
        self.w_config_accounts_password_label = QtW.QLabel("Password:")
        self.w_config_accounts_layout.addWidget(self.w_config_accounts_password_label, 2, 0)
        self.w_config_accounts_password_edit = QtW.QLineEdit()
        self.w_config_accounts_layout.addWidget(self.w_config_accounts_password_edit, 2, 1)
        self.w_config_accounts_add_button = QtW.QPushButton("Add")
        self.w_config_accounts_layout.addWidget(self.w_config_accounts_add_button, 2, 2)
        self.w_config_accounts_table.setRowCount(1)

        self.w_config_banned_ips_group = QtW.QGroupBox("Banned IPs")
        self.w_config_layout.addWidget(self.w_config_banned_ips_group, 3, 1)
        self.w_config_banned_ips_layout = QtW.QGridLayout()
        self.w_config_banned_ips_group.setLayout(self.w_config_banned_ips_layout)
        self.w_config_banned_ips_table = QtW.QTableWidget()
        self.w_config_banned_ips_table.setColumnCount(2)
        self.w_config_banned_ips_table.setHorizontalHeaderItem(0, QtW.QTableWidgetItem("IP"))
        self.w_config_banned_ips_table.horizontalHeader().setSectionResizeMode(0, QtW.QHeaderView.ResizeMode.Stretch)
        self.w_config_banned_ips_table.setHorizontalHeaderItem(1, QtW.QTableWidgetItem("Reason"))
        self.w_config_banned_ips_table.horizontalHeader().setSectionResizeMode(1, QtW.QHeaderView.ResizeMode.Stretch)
        self.w_config_banned_ips_layout.addWidget(self.w_config_banned_ips_table, 0, 0, 1, 3)
        self.w_config_banned_ips_ip_label = QtW.QLabel("IP:")
        self.w_config_banned_ips_layout.addWidget(self.w_config_banned_ips_ip_label, 1, 0)
        self.w_config_banned_ips_ip_edit = QtW.QLineEdit()
        self.w_config_banned_ips_layout.addWidget(self.w_config_banned_ips_ip_edit, 1, 1)
        self.w_config_banned_ips_reason_label = QtW.QLabel("Reason:")
        self.w_config_banned_ips_layout.addWidget(self.w_config_banned_ips_reason_label, 2, 0)
        self.w_config_banned_ips_reason_edit = QtW.QLineEdit()
        self.w_config_banned_ips_layout.addWidget(self.w_config_banned_ips_reason_edit, 2, 1)
        self.w_config_banned_ips_add_button = QtW.QPushButton("Add")
        self.w_config_banned_ips_layout.addWidget(self.w_config_banned_ips_add_button, 2, 2)

        self.w_config_banned_uuids_group = QtW.QGroupBox("Banned UUIDs")
        self.w_config_layout.addWidget(self.w_config_banned_uuids_group, 3, 2)
        self.w_config_banned_uuids_layout = QtW.QGridLayout()
        self.w_config_banned_uuids_group.setLayout(self.w_config_banned_uuids_layout)
        self.w_config_banned_uuids_table = QtW.QTableWidget()
        self.w_config_banned_uuids_table.setColumnCount(2)
        self.w_config_banned_uuids_table.setHorizontalHeaderItem(0, QtW.QTableWidgetItem("UUID"))
        self.w_config_banned_uuids_table.horizontalHeader().setSectionResizeMode(0, QtW.QHeaderView.ResizeMode.Stretch)
        self.w_config_banned_uuids_table.setHorizontalHeaderItem(1, QtW.QTableWidgetItem("Reason"))
        self.w_config_banned_uuids_table.horizontalHeader().setSectionResizeMode(1, QtW.QHeaderView.ResizeMode.Stretch)
        self.w_config_banned_uuids_layout.addWidget(self.w_config_banned_uuids_table, 0, 0, 1, 3)
        self.w_config_banned_uuids_uuid_label = QtW.QLabel("UUID:")
        self.w_config_banned_uuids_layout.addWidget(self.w_config_banned_uuids_uuid_label, 1, 0)
        self.w_config_banned_uuids_uuid_edit = QtW.QLineEdit()
        self.w_config_banned_uuids_layout.addWidget(self.w_config_banned_uuids_uuid_edit, 1, 1)
        self.w_config_banned_uuids_reason_label = QtW.QLabel("Reason:")
        self.w_config_banned_uuids_layout.addWidget(self.w_config_banned_uuids_reason_label, 2, 0)
        self.w_config_banned_uuids_reason_edit = QtW.QLineEdit()
        self.w_config_banned_uuids_layout.addWidget(self.w_config_banned_uuids_reason_edit, 2, 1)
        self.w_config_banned_uuids_add_button = QtW.QPushButton("Add")
        self.w_config_banned_uuids_layout.addWidget(self.w_config_banned_uuids_add_button, 2, 2)

        self.w_config_layout.setRowStretch(4, 1)

        # Mods Tab
        self.w_mods_widget = QtW.QWidget()
        self.w_mods_layout = QtW.QVBoxLayout()
        self.w_mods_widget.setLayout(self.w_mods_layout)
        self.w_tab_widget.addTab(self.w_mods_widget, "Server Mods")

        self.w_mods_current_mods_layout = QtW.QHBoxLayout()
        self.w_mods_layout.addLayout(self.w_mods_current_mods_layout)
        self.w_mods_current_mods_label = QtW.QLabel("Current Mods: ")
        self.w_mods_current_mods_layout.addWidget(self.w_mods_current_mods_label)
        self.w_mods_current_mods_data = QtW.QLabel("0")
        self.w_mods_current_mods_layout.addWidget(self.w_mods_current_mods_data, 1)
        self.w_mods_mods_table = QtW.QTableWidget()
        self.w_mods_mods_table.setColumnCount(3)
        self.w_mods_mods_table.setHorizontalHeaderItem(0, QtW.QTableWidgetItem("Mod"))
        self.w_mods_mods_table.horizontalHeader().setSectionResizeMode(0, QtW.QHeaderView.ResizeMode.Stretch)
        self.w_mods_mods_table.setHorizontalHeaderItem(1, QtW.QTableWidgetItem("Path"))
        self.w_mods_mods_table.horizontalHeader().setSectionResizeMode(1, QtW.QHeaderView.ResizeMode.Stretch)
        self.w_mods_mods_table.setHorizontalHeaderItem(2, QtW.QTableWidgetItem("Status"))
        self.w_mods_mods_table.horizontalHeader().setSectionResizeMode(2, QtW.QHeaderView.ResizeMode.ResizeToContents)
        self.w_mods_layout.addWidget(self.w_mods_mods_table, 1)
        self.w_mods_directory_label = QtW.QLabel("Mod Directory")
        self.w_mods_layout.addWidget(self.w_mods_directory_label)
        self.w_mods_directory_layout = QtW.QHBoxLayout()
        self.w_mods_layout.addLayout(self.w_mods_directory_layout)
        self.w_mods_directory_edit = QtW.QLineEdit()
        self.w_mods_directory_edit.setEnabled(False)
        self.w_mods_directory_layout.addWidget(self.w_mods_directory_edit, 1)
        self.w_mods_directory_open_button = QtW.QPushButton("Open")
        self.w_mods_directory_layout.addWidget(self.w_mods_directory_open_button)

        # Customization Tab
        self.w_customization_widget = QtW.QWidget()
        self.w_customization_layout = QtW.QVBoxLayout()
        self.w_customization_widget.setLayout(self.w_customization_layout)
        self.w_tab_widget.addTab(self.w_customization_widget, "Customization")

        # Timers
        self.resource_timer = QtC.QTimer()
        self.resource_timer.setInterval(2000)
        self.resource_timer.timeout.connect(self.__update_resource_usage__)
        self.resource_timer.start()

    def __exit_action__(self):
        pass

    def __about_action__(self):
        pass

    def __general_command_send_clicked__(self):
        pass

    def __general_controls_start_clicked__(self):
        pass

    def __general_controls_restart_clicked__(self):
        pass

    def __general_controls_stop_clicked__(self):
        pass

    def __update_resource_usage__(self):
        if not self.w_tab_widget.isTabVisible(6):
            return
        sb_running = False
        self.w_stats_resource_cpu_gui_data.setText(f"{round(psutil.Process().cpu_percent(), 2)}%")
        self.w_stats_resource_ram_gui_data.setText(f"{round(psutil.Process().memory_percent(), 2)}%")
        for proc in psutil.process_iter():
            if "starbound_server" in proc.name():
                sb_running = True
                print(proc.pid)
                self.w_stats_resource_cpu_server_data.setText(f"{round(proc.cpu_percent() / psutil.cpu_count(), 2)}%")
                self.w_stats_resource_ram_server_data.setText(f"{round(proc.memory_percent(), 2)}%")
        if not sb_running:
            self.w_stats_resource_cpu_server_data.setText(f"-")
            self.w_stats_resource_ram_server_data.setText(f"-")
        self.w_stats_resource_cpu_total_data.setText(f"{psutil.cpu_percent()}%")
        self.w_stats_resource_ram_total_data.setText(f"{psutil.virtual_memory().percent}%")

    def __server_name_edited__(self, text):
        self.config["serverName"] = text
        with open(os.path.join("starbound_server.config"), "w") as file:
            json.dump(self.config, file, sort_keys=True, indent=2)

    def __server_port_edited__(self, text):
        pass

    def __max_players_edited__(self, text):
        pass

    def __team_size_edited__(self, text):
        pass

    def __network_bind_edited__(self, button_id):
        pass

def main():
    app = QtW.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    app.exec_()
